/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Clube;

import Controller.ControladorClube;
import JDBC.ConnectionFactory;
import Model.Clube.Clube;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaClube extends javax.swing.JPanel {

    /**
     * Creates new form TelaClube
     */
    public TelaClube() {
        initComponents();
        configurarAcessos();
        customizarLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarClube = new javax.swing.JButton();
        jButton2ListarClubes = new javax.swing.JButton();
        jButton3EditarClube = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5ExcluirClube = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClubes = new javax.swing.JTable();

        jButtonCadastrarClube.setText("Cadastrar Clube");
        jButtonCadastrarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClubeActionPerformed(evt);
            }
        });

        jButton2ListarClubes.setText("Listar Clubes");
        jButton2ListarClubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ListarClubesActionPerformed(evt);
            }
        });

        jButton3EditarClube.setText("Editar Clube");
        jButton3EditarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EditarClubeActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar Clube");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5ExcluirClube.setText("Excluir Clube");
        jButton5ExcluirClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirClubeActionPerformed(evt);
            }
        });

        tabelaClubes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "id", "Nome", "Ano de fundação", "País", "Saldo"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabelaClubes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaClubes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCadastrarClube)
                                                .addGap(60, 60, 60)
                                                .addComponent(jButton2ListarClubes,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(jButton3EditarClube,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addComponent(jButton5ExcluirClube,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2ListarClubes)
                                        .addComponent(jButton3EditarClube)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5ExcluirClube)
                                        .addComponent(jButtonCadastrarClube))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarClubeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCadastrarClubeActionPerformed

        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaCadastroClube telaCadastro = new TelaCadastroClube(framePai, true);

        telaCadastro.setVisible(true);

    }// GEN-LAST:event_jButtonCadastrarClubeActionPerformed

    private void jButton2ListarClubesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ListarClubesActionPerformed
        ControladorClube controladorClube = new ControladorClube();

        ConnectionFactory.iniciarTabelaClube();

        DefaultTableModel modelo = (DefaultTableModel) tabelaClubes.getModel();

        modelo.setNumRows(0);

        ArrayList<Clube> clubes = controladorClube.listarClubes();

        for (Clube clube : clubes) {

            Object[] linha = {
                    clube.getIdClube(),
                    clube.getNome(),
                    clube.getAnoDeFundacao(),
                    clube.getPais(),
                    String.format(java.util.Locale.US, "%.2f", clube.getSaldoAtual())
            };

            modelo.addRow(linha);

        }
    }// GEN-LAST:event_jButton2ListarClubesActionPerformed

    private void jButton3EditarClubeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3EditarClubeActionPerformed

        int linhaSelecionada = tabelaClubes.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                Object valorId = tabelaClubes.getValueAt(linhaSelecionada, 0);

                int id = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 0).toString());
                String nome = tabelaClubes.getValueAt(linhaSelecionada, 1).toString();
                int anoFundacao = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 2).toString());
                String pais = tabelaClubes.getValueAt(linhaSelecionada, 3).toString();

                java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

                TelaAlterarClube telaAlterarClube = new TelaAlterarClube(framePai, true, id, nome, anoFundacao, pais);

                telaAlterarClube.setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }// GEN-LAST:event_jButton3EditarClubeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        try {
            int idClube = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "ID do clube:"));

            ControladorClube controladorClube = new ControladorClube();

            ConnectionFactory.iniciarTabelaClube();

            Clube c = controladorClube.buscarClube(idClube);

            DefaultTableModel modelo = (DefaultTableModel) tabelaClubes.getModel();

            modelo.setNumRows(0);

            Object[] linha = {
                    c.getIdClube(),
                    c.getNome(),
                    c.getAnoDeFundacao(),
                    c.getPais(),
                    String.format(java.util.Locale.US, "%.2f", c.getSaldoAtual())
            };

            modelo.addRow(linha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clube não encontrado ou Operação cancelada");
        }
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ExcluirClubeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ExcluirClubeActionPerformed

        int linhaSelecionada = tabelaClubes.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                Object valorId = tabelaClubes.getValueAt(linhaSelecionada, 0);

                int id = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 0).toString());

                int resposta = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente excluir o clube?",
                        "Confirmar Exclusão de Clube",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (resposta == JOptionPane.YES_OPTION) {
                    ControladorClube controladorClube = new ControladorClube();

                    ConnectionFactory.iniciarTabelaClube();

                    controladorClube.iniciarExclusaoDeClube(id);
                    ((DefaultTableModel) tabelaClubes.getModel()).removeRow(linhaSelecionada);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }// GEN-LAST:event_jButton5ExcluirClubeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2ListarClubes;
    private javax.swing.JButton jButton3EditarClube;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5ExcluirClube;
    private javax.swing.JButton jButtonCadastrarClube;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClubes;
    // End of variables declaration//GEN-END:variables

    private void customizarLayout() {
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(24, 24));
        this.setBackground(View.Theme.BACKGROUND);
        this.setBorder(new javax.swing.border.EmptyBorder(32, 32, 32, 32));

        // Header
        javax.swing.JPanel header = new javax.swing.JPanel(new java.awt.BorderLayout());
        header.setBackground(View.Theme.BACKGROUND);
        
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("Clubes");
        lblTitle.setFont(View.Theme.FONT_TITLE);
        lblTitle.setForeground(View.Theme.CINZA_ESCURO);
        header.add(lblTitle, java.awt.BorderLayout.WEST);

        // Actions
        javax.swing.JPanel actions = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 12, 0));
        actions.setBackground(View.Theme.BACKGROUND);
        
        View.Theme.styleButtonPrimary(jButton4); // Buscar
        View.Theme.styleButtonSecondary(jButton2ListarClubes);
        View.Theme.styleButtonSecondary(jButton3EditarClube);
        View.Theme.styleButtonDanger(jButton5ExcluirClube);
        View.Theme.styleButtonSuccess(jButtonCadastrarClube);
        
        actions.add(jButton4);
        actions.add(jButton2ListarClubes);
        actions.add(jButton3EditarClube);
        actions.add(jButton5ExcluirClube);
        actions.add(jButtonCadastrarClube);

        header.add(actions, java.awt.BorderLayout.EAST);

        this.add(header, java.awt.BorderLayout.NORTH);

        // Table
        View.Theme.styleTable(tabelaClubes);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(View.Theme.CINZA_CLARO_PAINEL));
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        this.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    private void configurarAcessos() {
        if (Model.Sessao.getUsuarioLogado() == null) {
            return;
        }
        int nivel = Model.Sessao.getUsuarioLogado().getNivel_usuario();
        if (nivel == 1 || nivel == 2) { // GF or Op
            jButtonCadastrarClube.setEnabled(false);
            jButton2ListarClubes.setEnabled(false);
            jButton3EditarClube.setEnabled(false);
            jButton4.setEnabled(false); // Buscar
            jButton5ExcluirClube.setEnabled(false);
        }
    }
}
