/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Jogador;

import Controller.ControladorFinanceiro;
import View.Usuario.TelaUsuario;
import Controller.ControladorJogador;
import Controller.ControladorUsuario;
import DataAcessObject.JogadorDAO;
import JDBC.ConnectionFactory;
import Model.Jogador.Jogador;
import Model.Usuario.Usuario;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mardegan
 */
public class TelaJogador extends javax.swing.JPanel {

    /**
     * Creates new form TelaJogador
     */
    public TelaJogador() {
        initComponents();
    }

    public static void main(String args[]) {
        /* Define o visual (Look and Feel) Nimbus para a tabela ficar bonita */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        /* Cria e exibe o JFrame que conterá o painel da tabela */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Testando Tela de Jogadores");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel de listagem
                TelaJogador painelJogador = new TelaJogador();

                frameTeste.setContentPane(painelJogador);

                // Ajusta o tamanho da janela e centraliza no meio do seu monitor
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaJogadores = new javax.swing.JTable();
        botaoComprar = new javax.swing.JButton();
        botaoVender = new javax.swing.JButton();
        botaoVerDetalhes = new javax.swing.JButton();
        botaoListar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        tabelaJogadores.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "id", "Nome", "Número", "Posição", "Valor"
                }));
        jScrollPane1.setViewportView(tabelaJogadores);

        botaoComprar.setText("Comprar");
        botaoComprar.addActionListener(this::botaoComprarActionPerformed);

        botaoVender.setText("Vender");
        botaoVender.addActionListener(this::botaoVenderActionPerformed);

        botaoVerDetalhes.setText("Ver Detalhes");
        botaoVerDetalhes.addActionListener(this::botaoVerDetalhesActionPerformed);

        botaoListar.setText("Listar");
        botaoListar.addActionListener(this::botaoListarActionPerformed);

        botaoEditar.setText("Editar");

        botaoBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botaoComprar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoVender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259,
                                        Short.MAX_VALUE)
                                .addComponent(botaoBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoVerDetalhes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 112, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botaoComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 51,
                                                Short.MAX_VALUE)
                                        .addComponent(botaoVender, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoVerDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoListar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVenderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVenderActionPerformed
        int linhaSelecionada = tabelaJogadores.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {

                int id = Integer.parseInt(tabelaJogadores.getValueAt(linhaSelecionada, 0).toString());

                ControladorJogador controladorJogador = new ControladorJogador();

                ConnectionFactory.iniciarTabelaJogador();

                Jogador jogador = DataAcessObject.JogadorDAO.buscarJogadorPorId(id);
                controladorJogador.iniciarVendaDeJogador(id);

                ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();
                controladorFinanceiro.iniciarCadastroDeReceitas("Transferência", jogador.getValor(),
                        "Venda de Jogador " + jogador.getNome() + ", " + jogador.getValor() + "R$", "Receita", null,
                        id);

                // Refresh the table to remove the sold player
                ((javax.swing.table.DefaultTableModel) tabelaJogadores.getModel()).removeRow(linhaSelecionada);


            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }// GEN-LAST:event_botaoVenderActionPerformed

    private void botaoVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {
        int linhaSelecionada = tabelaJogadores.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um jogador.");
            return;
        }

        int idJogador = (int) tabelaJogadores.getValueAt(linhaSelecionada, 0);

        Jogador jogador = JogadorDAO.buscarJogadorPorId(idJogador);

        if (jogador != null) {
            TelaDetalhesJogador telaDetalhes = new TelaDetalhesJogador(null, true);
            telaDetalhes.preencherDados(jogador);
            telaDetalhes.setVisible(true);
        }
    }

    private void botaoComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoComprarActionPerformed
        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaCadastroJogador telaCadastro = new TelaCadastroJogador(framePai, true);
        telaCadastro.setVisible(true);
    }// GEN-LAST:event_botaoComprarActionPerformed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoListarActionPerformed
        ControladorJogador controladorJogador = new ControladorJogador();

        JDBC.ConnectionFactory.iniciarTabelaJogador();

        DefaultTableModel modelo = (DefaultTableModel) tabelaJogadores.getModel();

        modelo.setNumRows(0);

        ArrayList<Jogador> jogadores = controladorJogador.iniciarListagemDeJogador();

        for (Jogador jogador : jogadores) {

            Object[] linha = {
                    jogador.getIdJogador(),
                    jogador.getNome(),
                    jogador.getNumero_da_camisa(),
                    jogador.getPosicao(),
                    jogador.getValor()
            };

            modelo.addRow(linha);
        }
    }// GEN-LAST:event_botaoListarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoComprar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoListar;
    private javax.swing.JButton botaoVender;
    private javax.swing.JButton botaoVerDetalhes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaJogadores;
    // End of variables declaration//GEN-END:variables
}
