/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Jogador;

import Controller.ControladorFinanceiro;
import Controller.ControladorJogador;
import Model.Jogador.Jogador;
import Model.Partida.Partida;
import java.util.Date;

/**
 *
 * @author mardegan
 */
public class TelaEditarJogador extends javax.swing.JDialog {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(TelaEditarJogador.class.getName());

        /**
         * Creates new form TelaEditarJogador
         */
        public TelaEditarJogador(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
        setTitle("Editar Jogador");
        }

        public TelaEditarJogador(java.awt.Frame parent, boolean modal, Jogador jogador) {
                super(parent, modal);
                initComponents();
                this.campoId.setText(String.valueOf(jogador.getIdJogador()));
                this.campoNome.setText(jogador.getNome());
                this.campoNacionalidade.setText(jogador.getNacionalidade());
                if (jogador.getData_de_nascimento() != null) {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    this.campoDataNascimento.setText(sdf.format(jogador.getData_de_nascimento()));
                }
                this.campoPosicao.setSelectedItem(jogador.getPosicao());
                this.campoNumeroCamisa.setText(String.valueOf(jogador.getNumero_da_camisa()));
                this.campoTempoContrato.setText(String.valueOf(jogador.getTempo_de_contrato()));
                this.campoSalario.setText(String.valueOf(jogador.getSalario()));
                this.campoValorMercado.setText(String.valueOf(jogador.getValor()));
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                botaoConfirmar = new javax.swing.JButton();
                jLabelId = new javax.swing.JLabel();
                campoId = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                campoNome = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                campoNacionalidade = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                campoPosicao = new javax.swing.JComboBox<>();
                jLabel6 = new javax.swing.JLabel();
                campoNumeroCamisa = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                campoTempoContrato = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                campoSalario = new javax.swing.JTextField();
                campoDataNascimento = new javax.swing.JFormattedTextField();
                campoValorMercado = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(220, 220, 220));

                jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                jLabel1.setText("Editar Jogador");

                botaoConfirmar.setText("Confirmar");
                botaoConfirmar.addActionListener(this::botaoConfirmarActionPerformed);

                jLabel2.setForeground(new java.awt.Color(0, 0, 0));
                jLabelId.setForeground(new java.awt.Color(0, 0, 0));
                jLabelId.setText("ID");
                campoId.setBackground(new java.awt.Color(200, 200, 200));

                jLabel2.setText("Nome");

                campoNome.setBackground(new java.awt.Color(200, 200, 200));
                campoNome.addActionListener(this::campoNomeActionPerformed);

                jLabel3.setForeground(new java.awt.Color(0, 0, 0));
                jLabel3.setText("Data de Nascimento");

                campoNacionalidade.setBackground(new java.awt.Color(200, 200, 200));
                campoNacionalidade.addActionListener(this::campoNacionalidadeActionPerformed);

                jLabel4.setForeground(new java.awt.Color(0, 0, 0));
                jLabel4.setText("Nacionalidade");

                jLabel5.setBackground(new java.awt.Color(0, 0, 0));
                jLabel5.setForeground(new java.awt.Color(0, 0, 0));
                jLabel5.setText("Posição");

                campoPosicao.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Goleiro", "Lateral Direito",
                                                "Lateral Esquerdo", "Zagueiro", "Meio Campo", "Ponta Direito",
                                                "Ponta Esquerdo", "Atacante" }));
                campoPosicao.addActionListener(this::campoPosicaoActionPerformed);

                jLabel6.setBackground(new java.awt.Color(0, 0, 0));
                jLabel6.setForeground(new java.awt.Color(0, 0, 0));
                jLabel6.setText("Número da Camisa");

                campoNumeroCamisa.setBackground(new java.awt.Color(200, 200, 200));

                jLabel7.setForeground(new java.awt.Color(0, 0, 0));
                jLabel7.setText("(dd/mm/aaaa)");

                jLabel8.setForeground(new java.awt.Color(0, 0, 0));
                jLabel8.setText("Tempo de Contrato");

                jLabel9.setForeground(new java.awt.Color(0, 0, 0));
                jLabel9.setText("Em anos");

                campoTempoContrato.setBackground(new java.awt.Color(200, 200, 200));

                jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                jLabel10.setText("Salário");
                jLabel10.setToolTipText("");

                campoSalario.setBackground(new java.awt.Color(200, 200, 200));

                campoDataNascimento.setBackground(new java.awt.Color(200, 200, 200));
                try {
                        campoDataNascimento.setFormatterFactory(
                                        new javax.swing.text.DefaultFormatterFactory(
                                                        new javax.swing.text.MaskFormatter("##/##/####")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }

                campoValorMercado.setBackground(new java.awt.Color(200, 200, 200));

                jLabel11.setForeground(new java.awt.Color(0, 0, 0));
                jLabel11.setText("Valor de Mercado");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(146, 146, 146)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addComponent(botaoConfirmar)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(14, 14, 14)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabelId)
                                                                                                                .addComponent(campoId,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(campoNome,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(campoNumeroCamisa,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(campoNacionalidade,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(campoDataNascimento,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(148, 148, 148)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(jLabel10)
                                                                                                                                .addComponent(jLabel9)
                                                                                                                                .addComponent(jLabel8)
                                                                                                                                .addComponent(campoTempoContrato)
                                                                                                                                .addComponent(campoSalario,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                132,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addComponent(campoValorMercado,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(campoPosicao,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                130,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(jLabel11))))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel1)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabelId)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(campoId,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel8))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(campoNome,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(campoNacionalidade,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(8, 8, 8)
                                                                                                .addComponent(jLabel3))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel9)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(campoTempoContrato,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel10)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(campoSalario,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(4, 4, 4)
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(campoDataNascimento,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(campoValorMercado,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(12, 12, 12)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(jLabel5))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(campoNumeroCamisa,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(campoPosicao,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel11)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                22,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(botaoConfirmar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(24, 24, 24)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoConfirmarActionPerformed
                int id = Integer.parseInt(campoId.getText());
                String nome = campoNome.getText().trim();
                String nacionalidade = campoNacionalidade.getText().trim();
                String posicao = campoPosicao.getSelectedItem().toString();
                float valor = -1;
                try { valor = Float.parseFloat(campoValorMercado.getText().trim()); } catch (Exception e) {}

                // caso o formato estej errado a validacao fica por conta do controller
                java.util.Date data_nascimento = null;
                try {
                        data_nascimento = new java.text.SimpleDateFormat("dd/MM/yyyy")
                                        .parse(campoDataNascimento.getText().trim());
                } catch (java.text.ParseException e) {
                }

                int numero_da_camisa = -1;
                try { numero_da_camisa = Integer.parseInt(campoNumeroCamisa.getText().trim()); } catch (Exception e) {}
                float salario = -1;
                try { salario = Float.parseFloat(campoSalario.getText().trim()); } catch (Exception e) {}
                int tempo_de_contrato = -1;
                try { tempo_de_contrato = Integer.parseInt(campoTempoContrato.getText().trim()); } catch (Exception e) {}

                ControladorJogador controladorJogador = new ControladorJogador();
                controladorJogador.iniciarAlteracaoDeInformacoesDeJogador(id, nome, data_nascimento,
                                nacionalidade, posicao, numero_da_camisa, salario, tempo_de_contrato, valor);

                dispose();
        }// GEN-LAST:event_botaoConfirmarActionPerformed

        private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNomeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_campoNomeActionPerformed

        private void campoNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNacionalidadeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_campoNacionalidadeActionPerformed

        private void campoPosicaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoPosicaoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_campoPosicaoActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botaoConfirmar;
        private javax.swing.JFormattedTextField campoDataNascimento;
        private javax.swing.JTextField campoNacionalidade;
        private javax.swing.JTextField campoId;
        private javax.swing.JLabel jLabelId;
        private javax.swing.JTextField campoNome;
        private javax.swing.JTextField campoNumeroCamisa;
        private javax.swing.JComboBox<String> campoPosicao;
        private javax.swing.JTextField campoSalario;
        private javax.swing.JTextField campoTempoContrato;
        private javax.swing.JTextField campoValorMercado;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration//GEN-END:variables
}
