/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Jogador;

/**
 *
 * @author Vinícius Mardegan
 */
public class TelaEmprestimoJogador extends javax.swing.JDialog {

    /**
     * Creates new form TelaEmprestimoJogador
     */
    public TelaEmprestimoJogador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizarCamposVisiveis();
    }

    private void atualizarCamposVisiveis() {
        String tipo = (String) comboTipoEmprestimo.getSelectedItem();
        boolean isEntrada = "Empréstimo de Entrada".equals(tipo);

        if (isEntrada) {
            lblNomeJogador.setVisible(true);
            campoNomeJogador.setVisible(true);
            lblNacionalidade.setVisible(true);
            campoNacionalidade.setVisible(true);
            lblDataNascimento.setVisible(true);
            lblDataNascimentoFormato.setVisible(true);
            campoDataNascimento.setVisible(true);
            lblNumeroCamisa.setVisible(true);
            campoNumeroCamisa.setVisible(true);
            lblPosicao.setVisible(true);
            campoPosicao.setVisible(true);
            lblSalario.setVisible(true);
            campoSalario.setVisible(true);
            lblTempoContrato.setVisible(true);
            campoTempoContrato.setVisible(true);
            lblTempoContratoAnos.setVisible(true);

            lblIdJogador.setVisible(false);
            campoIdJogador.setVisible(false);
        } else {
            lblNomeJogador.setVisible(false);
            campoNomeJogador.setVisible(false);
            lblNacionalidade.setVisible(false);
            campoNacionalidade.setVisible(false);
            lblDataNascimento.setVisible(false);
            lblDataNascimentoFormato.setVisible(false);
            campoDataNascimento.setVisible(false);
            lblNumeroCamisa.setVisible(false);
            campoNumeroCamisa.setVisible(false);
            lblPosicao.setVisible(false);
            campoPosicao.setVisible(false);
            lblSalario.setVisible(false);
            campoSalario.setVisible(false);
            lblTempoContrato.setVisible(false);
            campoTempoContrato.setVisible(false);
            lblTempoContratoAnos.setVisible(false);

            lblIdJogador.setVisible(true);
            campoIdJogador.setVisible(true);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTipoEmprestimo = new javax.swing.JLabel();
        comboTipoEmprestimo = new javax.swing.JComboBox<>();
        lblValorEmprestimo = new javax.swing.JLabel();
        campoValorEmprestimo = new javax.swing.JTextField();
        lblNomeJogador = new javax.swing.JLabel();
        campoNomeJogador = new javax.swing.JTextField();
        lblNacionalidade = new javax.swing.JLabel();
        campoNacionalidade = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        lblDataNascimentoFormato = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JFormattedTextField();
        lblNumeroCamisa = new javax.swing.JLabel();
        campoNumeroCamisa = new javax.swing.JTextField();
        lblPosicao = new javax.swing.JLabel();
        campoPosicao = new javax.swing.JComboBox<>();
        lblSalario = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        lblTempoContrato = new javax.swing.JLabel();
        lblTempoContratoAnos = new javax.swing.JLabel();
        campoTempoContrato = new javax.swing.JTextField();
        lblIdJogador = new javax.swing.JLabel();
        campoIdJogador = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimo de Jogador");

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Empréstimo de Jogador");

        lblTipoEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoEmprestimo.setText("Tipo de Empréstimo:");

        comboTipoEmprestimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empréstimo de Entrada", "Empréstimo de Saída" }));
        comboTipoEmprestimo.addActionListener(this::comboTipoEmprestimoActionPerformed);

        lblValorEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        lblValorEmprestimo.setText("Valor do Empréstimo:");

        campoValorEmprestimo.setBackground(new java.awt.Color(200, 200, 200));

        lblNomeJogador.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeJogador.setText("Nome do Jogador:");

        campoNomeJogador.setBackground(new java.awt.Color(200, 200, 200));

        lblNacionalidade.setForeground(new java.awt.Color(0, 0, 0));
        lblNacionalidade.setText("Nacionalidade:");

        campoNacionalidade.setBackground(new java.awt.Color(200, 200, 200));

        lblDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        lblDataNascimento.setText("Data Nasc:");

        lblDataNascimentoFormato.setForeground(new java.awt.Color(0, 0, 0));
        lblDataNascimentoFormato.setText("(dd/mm/aaaa)");

        campoDataNascimento.setBackground(new java.awt.Color(200, 200, 200));
        try {
            campoDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblNumeroCamisa.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroCamisa.setText("Número da Camisa:");

        campoNumeroCamisa.setBackground(new java.awt.Color(200, 200, 200));

        lblPosicao.setForeground(new java.awt.Color(0, 0, 0));
        lblPosicao.setText("Posição:");

        campoPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goleiro", "Lateral Direito", "Lateral Esquerdo", "Zagueiro", "Meio Campo", "Ponta Direito", "Ponta Esquerdo", "Atacante" }));

        lblSalario.setForeground(new java.awt.Color(0, 0, 0));
        lblSalario.setText("Salário:");

        campoSalario.setBackground(new java.awt.Color(200, 200, 200));

        lblTempoContrato.setForeground(new java.awt.Color(0, 0, 0));
        lblTempoContrato.setText("Tempo Contrato:");

        lblTempoContratoAnos.setForeground(new java.awt.Color(0, 0, 0));
        lblTempoContratoAnos.setText("(em anos)");

        campoTempoContrato.setBackground(new java.awt.Color(200, 200, 200));

        lblIdJogador.setForeground(new java.awt.Color(0, 0, 0));
        lblIdJogador.setText("ID do Jogador:");

        campoIdJogador.setBackground(new java.awt.Color(200, 200, 200));

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(this::botaoConfirmarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoEmprestimo)
                            .addComponent(comboTipoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorEmprestimo)
                            .addComponent(campoValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeJogador)
                            .addComponent(campoNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNacionalidade)
                            .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNascimento)
                            .addComponent(lblDataNascimentoFormato)
                            .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdJogador)
                            .addComponent(lblPosicao)
                            .addComponent(campoPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalario)
                            .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTempoContrato)
                            .addComponent(lblTempoContratoAnos)
                            .addComponent(campoTempoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroCamisa)
                            .addComponent(campoNumeroCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(botaoConfirmar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEmprestimo)
                    .addComponent(lblIdJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoIdJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblValorEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNacionalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataNascimento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTempoContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempoContratoAnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTempoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPosicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimentoFormato)
                    .addComponent(lblNumeroCamisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboTipoEmprestimoActionPerformed
        atualizarCamposVisiveis();
    }// GEN-LAST:event_comboTipoEmprestimoActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoConfirmarActionPerformed
        String tipo = (String) comboTipoEmprestimo.getSelectedItem();

        try {
            float valorEmprestimo = -1;
            try {
                valorEmprestimo = Float.parseFloat(campoValorEmprestimo.getText().trim());
            } catch (NumberFormatException e) {
            }

            int tempoContrato = -1;
            try {
                tempoContrato = Integer.parseInt(campoTempoContrato.getText().trim());
            } catch (NumberFormatException e) {
            }

            if ("Empréstimo de Entrada".equals(tipo)) {
                String nomeJogador = campoNomeJogador.getText().trim();
                String nacionalidade = campoNacionalidade.getText().trim();
                String posicao = campoPosicao.getSelectedItem().toString();

                float salario = -1;
                try {
                    salario = Float.parseFloat(campoSalario.getText().trim());
                } catch (NumberFormatException e) {
                }

                java.util.Date dataNascimento = null;
                try {
                    dataNascimento = new java.text.SimpleDateFormat("dd/MM/yyyy")
                            .parse(campoDataNascimento.getText().trim());
                } catch (java.text.ParseException e) {
                }

                int numeroCamisa = -1;
                try {
                    numeroCamisa = Integer.parseInt(campoNumeroCamisa.getText().trim());
                } catch (NumberFormatException e) {
                }

                Model.Jogador.Elenco elenco = new Model.Jogador.Elenco();
                int result = elenco.emprestarJogadorEntrada(nomeJogador, dataNascimento, nacionalidade, posicao,
                        numeroCamisa, salario, tempoContrato, valorEmprestimo);

                if (result > 0) {
                    dispose();
                }

            } else {
                // Empréstimo de Saída
                int idJogador = -1;
                try {
                    idJogador = Integer.parseInt(campoIdJogador.getText().trim());
                } catch (NumberFormatException e) {
                }

                Model.Jogador.Elenco elenco = new Model.Jogador.Elenco();
                int result = elenco.emprestarJogadorSaida(idJogador, valorEmprestimo);

                if (result > 0) {
                    dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Erro: Jogador não encontrado ou já emprestado!");
                }
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }// GEN-LAST:event_botaoConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JFormattedTextField campoDataNascimento;
    private javax.swing.JTextField campoIdJogador;
    private javax.swing.JTextField campoNacionalidade;
    private javax.swing.JTextField campoNomeJogador;
    private javax.swing.JTextField campoNumeroCamisa;
    private javax.swing.JComboBox<String> campoPosicao;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JTextField campoTempoContrato;
    private javax.swing.JTextField campoValorEmprestimo;
    private javax.swing.JComboBox<String> comboTipoEmprestimo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDataNascimentoFormato;
    private javax.swing.JLabel lblIdJogador;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNomeJogador;
    private javax.swing.JLabel lblNumeroCamisa;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTempoContrato;
    private javax.swing.JLabel lblTempoContratoAnos;
    private javax.swing.JLabel lblTipoEmprestimo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorEmprestimo;
    // End of variables declaration//GEN-END:variables
}
