/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Relatorio;

import Charts.RelatorioLinhaTempoFinanceiro;
import Charts.RelatorioBarrasDespesas;
import Charts.RelatorioPizzaReceitas;
import Controller.ControladorRelatorio;
import Model.TransacaoFinanceira.TransacaoFinanceira;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import javax.swing.JCheckBox;

/**
 *
 * @author Cauan
 */
public class TelaRelatorioFinanceiro extends javax.swing.JPanel {

    private List<JCheckBox> listaReceitas;
    private List<JCheckBox> listaDespesas;

    /**
     * Creates new form TelaRelatorioFinanceiro
     */
    public TelaRelatorioFinanceiro() {

        initComponents();

        listaReceitas = Arrays.asList(chkBilheteria, chkPatrocinio, chkProdutos, chkSocio, chkPremiacoes,
                chkTransferenciasRec);
        listaDespesas = Arrays.asList(chkInfraestrutura, chkProducao, chkSaude, chkSalarios, chkViagens,
                chkTransferenciasDesp);

        customizarLayout();

        jComboBox1Tipo.addActionListener(e -> gerenciarFiltrosEmTela());

        listaReceitas.forEach(chk -> chk.setEnabled(false));
        listaDespesas.forEach(chk -> chk.setEnabled(false));
        chkOutras.setEnabled(false);
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Tela de Relatório Financeiro");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel
                TelaRelatorioFinanceiro painelFinanceiro = new TelaRelatorioFinanceiro();

                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelFinanceiro);

                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoDataNascimento = new javax.swing.JFormattedTextField();
        jComboBox1Tipo = new javax.swing.JComboBox<>();
        chkBilheteria = new javax.swing.JCheckBox();
        chkPatrocinio = new javax.swing.JCheckBox();
        chkProdutos = new javax.swing.JCheckBox();
        chkSocio = new javax.swing.JCheckBox();
        chkPremiacoes = new javax.swing.JCheckBox();
        chkOutras = new javax.swing.JCheckBox();
        chkInfraestrutura = new javax.swing.JCheckBox();
        chkProducao = new javax.swing.JCheckBox();
        chkSaude = new javax.swing.JCheckBox();
        chkSalarios = new javax.swing.JCheckBox();
        chkViagens = new javax.swing.JCheckBox();
        botaoGerarRelatorioFinanceiro = new javax.swing.JButton();
        campoPeriodoFinal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        Final = new javax.swing.JLabel();
        campoPeriodoInicial1 = new javax.swing.JFormattedTextField();
        chkTransferenciasRec = new javax.swing.JCheckBox();
        chkTransferenciasDesp = new javax.swing.JCheckBox();

        campoDataNascimento.setBackground(new java.awt.Color(200, 200, 200));
        try {
            campoDataNascimento.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBox1Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Receita", "Despesa" }));

        chkBilheteria.setText("Bilheteria");
        chkBilheteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBilheteriaActionPerformed(evt);
            }
        });

        chkPatrocinio.setText("Patrocínio");

        chkProdutos.setText("Produtos");

        chkSocio.setText("Plano sócio-torcedor");

        chkPremiacoes.setText("Premiações");

        chkOutras.setText("Outras");

        chkInfraestrutura.setText("Infraestrutura");

        chkProducao.setText("Produção");

        chkSaude.setText("Saúde e Fisioterapia");

        chkSalarios.setText("Salários e Encargos");

        chkViagens.setText("Viagens e Logísticas");
        chkViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViagensActionPerformed(evt);
            }
        });

        botaoGerarRelatorioFinanceiro.setText("Gerar");
        botaoGerarRelatorioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioFinanceiroActionPerformed(evt);
            }
        });

        campoPeriodoFinal.setBackground(new java.awt.Color(200, 200, 200));
        try {
            campoPeriodoFinal.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoPeriodoFinal.setText("24/06/2026");

        jLabel1.setText("Início");

        Final.setText("Final");

        campoPeriodoInicial1.setBackground(new java.awt.Color(200, 200, 200));
        try {
            campoPeriodoInicial1.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoPeriodoInicial1.setText("01/01/2001");

        chkTransferenciasRec.setText("Transferências");

        chkTransferenciasDesp.setText("Transferências");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(chkProdutos)
                                                        .addComponent(chkSocio)
                                                        .addComponent(chkPatrocinio)
                                                        .addComponent(chkBilheteria)
                                                        .addComponent(chkTransferenciasRec)
                                                        .addComponent(chkPremiacoes))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(chkInfraestrutura)
                                                        .addComponent(chkProducao)
                                                        .addComponent(chkSaude)
                                                        .addComponent(chkSalarios)
                                                        .addComponent(chkViagens)
                                                        .addComponent(chkTransferenciasDesp))
                                                .addGap(90, 90, 90))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(campoPeriodoInicial1)
                                                                .addGap(106, 106, 106))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(156, 156, 156)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Final,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGap(24, 24, 24))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(campoPeriodoFinal,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(156, 156, 156))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(chkOutras)
                                                        .addComponent(botaoGerarRelatorioFinanceiro))
                                                .addContainerGap())))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(chkInfraestrutura)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkProducao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkSaude)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkSalarios)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(chkViagens)
                                                        .addComponent(chkPremiacoes,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkBilheteria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkPatrocinio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkProdutos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkSocio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkTransferenciasRec)
                                        .addComponent(chkTransferenciasDesp))
                                .addGap(16, 16, 16)
                                .addComponent(chkOutras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(Final))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoPeriodoInicial1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(botaoGerarRelatorioFinanceiro)
                                .addGap(17, 17, 17)));
    }// </editor-fold>//GEN-END:initComponents

    private void chkBilheteriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkBilheteriaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chkBilheteriaActionPerformed

    private void chkViagensActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkViagensActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chkViagensActionPerformed

    private void botaoGerarRelatorioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoGerarRelatorioFinanceiroActionPerformed

        ControladorRelatorio controladorRelatorio = new ControladorRelatorio();

        java.util.Date periodoInicial = null;
        java.util.Date periodoFinal = null;
        try {
            periodoInicial = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(campoPeriodoInicial1.getText().trim());
            periodoFinal = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(campoPeriodoFinal.getText().trim());
        } catch (java.text.ParseException e) {
        }

        ArrayList<String> selecionados = new ArrayList<>();

        ArrayList<TransacaoFinanceira> transacao = null;

        switch (jComboBox1Tipo.getSelectedItem().toString()) {
            case "Geral":
                transacao = controladorRelatorio.exibirRelatorioFinanceiroGeral(periodoInicial, periodoFinal, "ambos");

                exibirRelatorioDeTransacoes(transacao);
                break;

            case "Receita":
                for (JCheckBox chk : listaReceitas) {
                    if (chk.isSelected()) {
                        selecionados.add(chk.getText());
                    }
                }

                if (chkOutras.isSelected()) {
                    selecionados.add(chkOutras.getText());
                }

                transacao = controladorRelatorio.exibirRelatorioReceitas(periodoInicial, periodoFinal, selecionados,
                        "Receita");

                exibirRelatorioDeReceita(transacao);
                break;

            case "Despesa":

                for (JCheckBox chk : listaDespesas) {
                    if (chk.isSelected()) {
                        selecionados.add(chk.getText());
                    }
                }

                if (chkOutras.isSelected()) {
                    selecionados.add(chkOutras.getText());
                }

                transacao = controladorRelatorio.exibirRelatorioDespesas(periodoInicial, periodoFinal, selecionados,
                        "Despesa");

                exibirRelatorioDeDespesa(transacao);
                break;
        }
    }// GEN-LAST:event_botaoGerarRelatorioFinanceiroActionPerformed

    private void exibirRelatorioDeTransacoes(ArrayList<TransacaoFinanceira> transacoes) {
        javax.swing.JFrame janelaPai = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RelatorioLinhaTempoFinanceiro telaGrafico = new RelatorioLinhaTempoFinanceiro(janelaPai, transacoes);
        telaGrafico.setVisible(true);
    }

    private void exibirRelatorioDeReceita(ArrayList<TransacaoFinanceira> transacoes) {
        javax.swing.JFrame janelaPai = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RelatorioPizzaReceitas telaGrafico = new RelatorioPizzaReceitas(janelaPai, transacoes);
        telaGrafico.setVisible(true);
    }

    private void exibirRelatorioDeDespesa(ArrayList<TransacaoFinanceira> transacoes) {
        javax.swing.JFrame janelaPai = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RelatorioBarrasDespesas telaGrafico = new RelatorioBarrasDespesas(janelaPai, transacoes);
        telaGrafico.setVisible(true);
    }

    private void gerenciarFiltrosEmTela() {

        String opcaoSelecionada = (String) jComboBox1Tipo.getSelectedItem();

        if ("Geral".equals(opcaoSelecionada)) {

            listaReceitas.forEach(chk -> chk.setEnabled(false));
            listaDespesas.forEach(chk -> chk.setEnabled(false));
            chkOutras.setEnabled(false);
        } else if ("Receita".equals(opcaoSelecionada)) {

            listaReceitas.forEach(chk -> chk.setEnabled(true));
            listaDespesas.forEach(chk -> {
                chk.setEnabled(false);
                chk.setSelected(false); // limpa a seleção para não enviar lixo no relatório
            });
            chkOutras.setEnabled(true);
        } else if ("Despesa".equals(opcaoSelecionada)) {

            listaDespesas.forEach(chk -> chk.setEnabled(true));
            listaReceitas.forEach(chk -> {
                chk.setEnabled(false);
                chk.setSelected(false);
            });
            chkOutras.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Final;
    private javax.swing.JButton botaoGerarRelatorioFinanceiro;
    private javax.swing.JFormattedTextField campoDataNascimento;
    private javax.swing.JFormattedTextField campoPeriodoFinal;
    private javax.swing.JFormattedTextField campoPeriodoInicial1;
    private javax.swing.JCheckBox chkBilheteria;
    private javax.swing.JCheckBox chkInfraestrutura;
    private javax.swing.JCheckBox chkOutras;
    private javax.swing.JCheckBox chkPatrocinio;
    private javax.swing.JCheckBox chkPremiacoes;
    private javax.swing.JCheckBox chkProducao;
    private javax.swing.JCheckBox chkProdutos;
    private javax.swing.JCheckBox chkSalarios;
    private javax.swing.JCheckBox chkSaude;
    private javax.swing.JCheckBox chkSocio;
    private javax.swing.JCheckBox chkTransferenciasDesp;
    private javax.swing.JCheckBox chkTransferenciasRec;
    private javax.swing.JCheckBox chkViagens;
    private javax.swing.JComboBox<String> jComboBox1Tipo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void customizarLayout() {
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.setBackground(View.Theme.BACKGROUND);

        javax.swing.JPanel container = new javax.swing.JPanel(new java.awt.GridBagLayout());
        container.setBackground(View.Theme.BACKGROUND);
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(8, 8, 8, 8);
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.anchor = java.awt.GridBagConstraints.WEST;

        // Title
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("Relatório Financeiro");
        lblTitle.setFont(View.Theme.FONT_TITLE);
        lblTitle.setForeground(View.Theme.CINZA_ESCURO);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(8, 8, 24, 8);
        container.add(lblTitle, gbc);

        // Reset insets
        gbc.insets = new java.awt.Insets(8, 8, 8, 8);
        gbc.gridwidth = 1;

        // Tipo Relatorio
        gbc.gridx = 0;
        gbc.gridy = 1;
        container.add(jLabel1, gbc);
        gbc.gridx = 1;
        gbc.gridy = 1;
        View.Theme.styleComboBox(jComboBox1Tipo);
        container.add(jComboBox1Tipo, gbc);

        // Periodo Inicial
        gbc.gridx = 0;
        gbc.gridy = 2;
        javax.swing.JLabel lblInicio = new javax.swing.JLabel("Início:");
        lblInicio.setFont(View.Theme.FONT_TEXT);
        container.add(lblInicio, gbc);
        gbc.gridx = 1;
        gbc.gridy = 2;
        View.Theme.styleTextField(campoPeriodoInicial1);
        container.add(campoPeriodoInicial1, gbc);

        // Periodo Final
        gbc.gridx = 0;
        gbc.gridy = 3;
        Final.setFont(View.Theme.FONT_TEXT);
        container.add(Final, gbc);
        gbc.gridx = 1;
        gbc.gridy = 3;
        View.Theme.styleTextField(campoPeriodoFinal);
        container.add(campoPeriodoFinal, gbc);

        // Checkboxes Wrapper
        javax.swing.JPanel pnlChecks = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 8, 8));
        pnlChecks.setBackground(View.Theme.BACKGROUND);

        java.util.List<javax.swing.JCheckBox> allChecks = new java.util.ArrayList<>();
        allChecks.addAll(listaReceitas);
        allChecks.addAll(listaDespesas);
        allChecks.add(chkOutras);

        for (javax.swing.JCheckBox chk : allChecks) {
            chk.setFont(View.Theme.FONT_TEXT);
            chk.setBackground(View.Theme.BACKGROUND);
            pnlChecks.add(chk);
        }

        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(16, 8, 16, 8);
        container.add(pnlChecks, gbc);

        // Button
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(24, 8, 8, 8);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        View.Theme.styleButtonSuccess(botaoGerarRelatorioFinanceiro);
        container.add(botaoGerarRelatorioFinanceiro, gbc);

        // Centering the form
        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.GridBagLayout());
        wrapper.setBackground(View.Theme.BACKGROUND);
        wrapper.add(container);

        this.add(wrapper, java.awt.BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
}
