/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Receita;

import Controller.ControladorFinanceiro;
import JDBC.ConnectionFactory;
import Model.Sessao;
import java.util.Date;

/**
 *
 * @author Cauan
 */
public class TelaAlterarReceita extends javax.swing.JDialog {

    /**
     * Creates new form TelaAlterarReceita
     */
    public TelaAlterarReceita(java.awt.Frame parent, boolean modal, int idReceita, String descricao, String categoria,
            float valor) {
        super(parent, modal);
        initComponents();
        setTitle("Alterar Receita");
        setLocationRelativeTo(null);
        idReceitaEditar.setText(Integer.toString(idReceita));

        for (int i = 0; i < jComboBox1Categoria.getItemCount(); i++) {
            if (jComboBox1Categoria.getItemAt(i).toString().equalsIgnoreCase(categoria)) {
                jComboBox1Categoria.setSelectedIndex(i);
                break;
            }
        }
        valorEntradaReceita.setText(Float.toString(valor));
        descricaoEntradaReceita.setText(descricao);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1Categoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorEntradaReceita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoEntradaReceita = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1EditarReceita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idReceitaEditar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilheteria", "Patrocínio", "Produtos", "Plano sócio-torcedor", "Premiações", "Transferências", "Outras", " " }));

        jLabel2.setText("Categoria");

        jLabel3.setText("Valor");

        descricaoEntradaReceita.setColumns(20);
        descricaoEntradaReceita.setRows(5);
        jScrollPane1.setViewportView(descricaoEntradaReceita);

        jLabel1.setText("Descrição");

        jButton1EditarReceita.setText("Editar");
        jButton1EditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EditarReceitaActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Receita");

        idReceitaEditar.setEditable(false);
        idReceitaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReceitaEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1Categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorEntradaReceita)
                    .addComponent(idReceitaEditar))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1EditarReceita)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idReceitaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorEntradaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1EditarReceita)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1EditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1EditarReceitaActionPerformed
        ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

        ConnectionFactory.iniciarTabelaTransacao();

        int idReceita = -1;
        try {
            idReceita = Integer.parseInt(idReceitaEditar.getText());
        } catch (NumberFormatException e) {
        }
        String categoria = (String) jComboBox1Categoria.getSelectedItem();
        
        float valor = -1f;
        try {
            valor = Float.parseFloat(valorEntradaReceita.getText());
        } catch (NumberFormatException e) {
        }
        String descricao = descricaoEntradaReceita.getText();

        int idClube = Sessao.getIdClubeAtual();
        controladorFinanceiro.iniciarEdicaoDeReceitas(idReceita, idClube, categoria, valor, descricao, "Receita");

        this.dispose();
    }// GEN-LAST:event_jButton1EditarReceitaActionPerformed

    private void idReceitaEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_idReceitaEditarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_idReceitaEditarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricaoEntradaReceita;
    private javax.swing.JTextField idReceitaEditar;
    private javax.swing.JButton jButton1EditarReceita;
    private javax.swing.JComboBox<String> jComboBox1Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorEntradaReceita;
    // End of variables declaration//GEN-END:variables
}
