/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Despesa;

import Controller.ControladorFinanceiro;
import JDBC.ConnectionFactory;
import Model.Sessao;

/**
 *
 * @author Cauan
 */
public class TelaAlterarDespesa extends javax.swing.JDialog {

    /**
     * Creates new form TelaAlterarDespesa
     */
    public TelaAlterarDespesa(java.awt.Frame parent, boolean modal, int idDespesa, String descricao, String categoria,
            float valor) {
        super(parent, modal);
        initComponents();
        setTitle("Alterar Despesa");
        setLocationRelativeTo(null);
        idDespesaEditar.setText(Integer.toString(idDespesa));

        for (int i = 0; i < jComboBox1Categoria.getItemCount(); i++) {
            if (jComboBox1Categoria.getItemAt(i).toString().equalsIgnoreCase(categoria)) {
                jComboBox1Categoria.setSelectedIndex(i);
                break;
            }
        }
        valorEntradaDespesa.setText(Float.toString(valor));
        descricaoEntradaDespesa.setText(descricao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        idDespesaEditar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1Categoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        valorEntradaDespesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoEntradaDespesa = new javax.swing.JTextArea();
        jButton1EditarDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Id Despesa");

        idDespesaEditar.setEditable(false);
        idDespesaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDespesaEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jComboBox1Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infraestrutura", "Produção", "Saúde e Fisioterapia", "Salários e Encargos", "Viagens e Logísticas", "Transferências", "Outras", " " }));

        jLabel3.setText("Valor");

        jLabel1.setText("Descrição");

        descricaoEntradaDespesa.setColumns(20);
        descricaoEntradaDespesa.setRows(5);
        jScrollPane1.setViewportView(descricaoEntradaDespesa);

        jButton1EditarDespesa.setText("Editar");
        jButton1EditarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EditarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1Categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorEntradaDespesa)
                    .addComponent(idDespesaEditar))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1EditarDespesa)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idDespesaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorEntradaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1EditarDespesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idDespesaEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_idDespesaEditarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_idDespesaEditarActionPerformed

    private void jButton1EditarDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1EditarDespesaActionPerformed
        ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

        ConnectionFactory.iniciarTabelaTransacao();

        int idDespesa = -1;
        try {
            idDespesa = Integer.parseInt(idDespesaEditar.getText());
        } catch (NumberFormatException e) {
        }
        String categoria = (String) jComboBox1Categoria.getSelectedItem();
        
        float valor = -1f;
        try {
            valor = Float.parseFloat(valorEntradaDespesa.getText());
        } catch (NumberFormatException e) {
        }
        String descricao = descricaoEntradaDespesa.getText();

        int idClube = Sessao.getIdClubeAtual();
        controladorFinanceiro.iniciarEdicaoDeDespesa(idDespesa, idClube, categoria, valor, descricao, "Despesa");

        this.dispose();
    }// GEN-LAST:event_jButton1EditarDespesaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricaoEntradaDespesa;
    private javax.swing.JTextField idDespesaEditar;
    private javax.swing.JButton jButton1EditarDespesa;
    private javax.swing.JComboBox<String> jComboBox1Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorEntradaDespesa;
    // End of variables declaration//GEN-END:variables
}
