/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Despesa;

import Controller.ControladorFinanceiro;
import JDBC.ConnectionFactory;

/**
 *
 * @author Cauan
 */
public class TelaCadastroDespesa extends javax.swing.JDialog {

        /**
         * Creates new form TelaCadastroDespesa
         */
        public TelaCadastroDespesa(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
        setTitle("Cadastro de Despesa");
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1Categoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        valorEntradaDespesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoEntradaDespesa = new javax.swing.JTextArea();
        jButton1CadastrarDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Categoria");

        jComboBox1Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infraestrutura", "Produção", "Saúde e Fisioterapia", "Salários e Encargos", "Viagens e Logísticas", "Transferências", "Outras", " " }));

        jLabel3.setText("Valor");

        jLabel1.setText("Descrição");

        descricaoEntradaDespesa.setColumns(20);
        descricaoEntradaDespesa.setRows(5);
        jScrollPane1.setViewportView(descricaoEntradaDespesa);

        jButton1CadastrarDespesa.setText("Cadastrar");
        jButton1CadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jComboBox1Categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorEntradaDespesa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1CadastrarDespesa)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorEntradaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1CadastrarDespesa)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jButton1CadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1CadastrarDespesaActionPerformed
                ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

                ConnectionFactory.iniciarTabelaTransacao();

                String categoria = (String) jComboBox1Categoria.getSelectedItem();
                float valor = -1f;
        try {
            valor = Float.parseFloat(valorEntradaDespesa.getText());
        } catch (NumberFormatException e) {
        }
                String descricao = descricaoEntradaDespesa.getText();

                controladorFinanceiro.iniciarCadastroDeDespesas(categoria, valor, descricao, "Despesa");

                this.dispose();
        }// GEN-LAST:event_jButton1CadastrarDespesaActionPerformed

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricaoEntradaDespesa;
    private javax.swing.JButton jButton1CadastrarDespesa;
    private javax.swing.JComboBox<String> jComboBox1Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorEntradaDespesa;
    // End of variables declaration//GEN-END:variables
}
