/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Despesa;

import Controller.ControladorFinanceiro;
import JDBC.ConnectionFactory;
import Model.Sessao;
import Model.TransacaoFinanceira.TransacaoFinanceira;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaDespesa extends javax.swing.JPanel {

    /**
     * Creates new form TelaDespesa
     */
    public TelaDespesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDespesas = new javax.swing.JTable();
        jButtonCadastrarDespesa = new javax.swing.JButton();
        jButton2ListarDespesas = new javax.swing.JButton();
        jButton3EditarDespesa = new javax.swing.JButton();
        jButton4BuscarDespesa = new javax.swing.JButton();
        jButton5ExcluirDespesa = new javax.swing.JButton();

        tabelaDespesas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "id", "descrição", "categoria", "valor", "data"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabelaDespesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaDespesas);

        jButtonCadastrarDespesa.setText("Cadastrar Despesa");
        jButtonCadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarDespesaActionPerformed(evt);
            }
        });

        jButton2ListarDespesas.setText("Listar Despesas");
        jButton2ListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ListarDespesasActionPerformed(evt);
            }
        });

        jButton3EditarDespesa.setText("Editar Despesa");
        jButton3EditarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EditarDespesaActionPerformed(evt);
            }
        });

        jButton4BuscarDespesa.setText("Buscar Despesa");
        jButton4BuscarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4BuscarDespesaActionPerformed(evt);
            }
        });

        jButton5ExcluirDespesa.setText("Excluir Despesa");
        jButton5ExcluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCadastrarDespesa)
                                                .addGap(60, 60, 60)
                                                .addComponent(jButton2ListarDespesas)
                                                .addGap(58, 58, 58)
                                                .addComponent(jButton3EditarDespesa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73,
                                                        Short.MAX_VALUE)
                                                .addComponent(jButton4BuscarDespesa)
                                                .addGap(57, 57, 57)
                                                .addComponent(jButton5ExcluirDespesa)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2ListarDespesas)
                                        .addComponent(jButton3EditarDespesa)
                                        .addComponent(jButton4BuscarDespesa)
                                        .addComponent(jButton5ExcluirDespesa)
                                        .addComponent(jButtonCadastrarDespesa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCadastrarDespesaActionPerformed

        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaCadastroDespesa telaCadastro = new TelaCadastroDespesa(framePai, true);

        telaCadastro.setVisible(true);
    }// GEN-LAST:event_jButtonCadastrarDespesaActionPerformed

    private void jButton2ListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ListarDespesasActionPerformed

        ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

        ConnectionFactory.iniciarTabelaTransacao();

        DefaultTableModel modelo = (DefaultTableModel) tabelaDespesas.getModel();

        modelo.setNumRows(0);

        ArrayList<TransacaoFinanceira> despesas = controladorFinanceiro.iniciarListagemDeDespesas();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (TransacaoFinanceira d : despesas) {

            Object[] linha = {
                    d.getIdTransacao(),
                    d.getDescricao(),
                    d.getCategoria(),
                    String.format(java.util.Locale.US, "%.2f", d.getValor()),
                    sdf.format(d.getData())
            };

            modelo.addRow(linha);

        }

    }// GEN-LAST:event_jButton2ListarDespesasActionPerformed

    private void jButton3EditarDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3EditarDespesaActionPerformed

        int linhaSelecionada = tabelaDespesas.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                Object valorId = tabelaDespesas.getValueAt(linhaSelecionada, 0);

                int id = Integer.parseInt(tabelaDespesas.getValueAt(linhaSelecionada, 0).toString());
                String descricao = tabelaDespesas.getValueAt(linhaSelecionada, 1).toString();
                String categoria = tabelaDespesas.getValueAt(linhaSelecionada, 2).toString();
                float valor = Float.parseFloat(tabelaDespesas.getValueAt(linhaSelecionada, 3).toString());

                java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

                TelaAlterarDespesa telaAlterarDespesa = new TelaAlterarDespesa(framePai, true, id, descricao, categoria,
                        valor);

                telaAlterarDespesa.setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }
    }// GEN-LAST:event_jButton3EditarDespesaActionPerformed

    private void jButton4BuscarDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4BuscarDespesaActionPerformed
        try {
            int idReceita = -1;
            try {
                idReceita = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "ID da despesa:"));
            } catch (NumberFormatException ex) {
            }

            ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

            ConnectionFactory.iniciarTabelaTransacao();

            TransacaoFinanceira r = controladorFinanceiro.iniciarBuscaDeDespesas(idReceita);

            DefaultTableModel modelo = (DefaultTableModel) tabelaDespesas.getModel();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            modelo.setNumRows(0);

            Object[] linha = {
                    r.getIdTransacao(),
                    r.getDescricao(),
                    r.getCategoria(),
                    String.format(java.util.Locale.US, "%.2f", r.getValor()),
                    sdf.format(r.getData())
            };

            modelo.addRow(linha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Despesa não encontrada ou Operação cancelada");
        }

    }// GEN-LAST:event_jButton4BuscarDespesaActionPerformed

    private void jButton5ExcluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ExcluirDespesaActionPerformed

        int linhaSelecionada = tabelaDespesas.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                Object valorId = tabelaDespesas.getValueAt(linhaSelecionada, 0);

                int idTransacao = Integer.parseInt(tabelaDespesas.getValueAt(linhaSelecionada, 0).toString());

                float valor = Float.parseFloat(tabelaDespesas.getValueAt(linhaSelecionada, 3).toString());

                int resposta = JOptionPane.showConfirmDialog(
                        null,
                        "O saldo do clube será somado por " + valor,
                        "Confirmar Exclusão de Despesa",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (resposta == JOptionPane.YES_OPTION) {
                    ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

                    ConnectionFactory.iniciarTabelaTransacao();

                    int idClube = Sessao.getIdClubeAtual();

                    controladorFinanceiro.iniciarExclusaoDeDespesa(idTransacao, idClube);
                    ((DefaultTableModel) tabelaDespesas.getModel()).removeRow(linhaSelecionada);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }// GEN-LAST:event_jButton5ExcluirDespesaActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Tela de Despesa");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel
                TelaDespesa painelTransacao = new TelaDespesa();

                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelTransacao);

                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2ListarDespesas;
    private javax.swing.JButton jButton3EditarDespesa;
    private javax.swing.JButton jButton4BuscarDespesa;
    private javax.swing.JButton jButton5ExcluirDespesa;
    private javax.swing.JButton jButtonCadastrarDespesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDespesas;
    // End of variables declaration//GEN-END:variables
}
