/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Usuario.TelaAutenticacaoUsuario;
import View.Usuario.TelaCadastroADM;
import DataAcessObject.UsuarioDAO;
import JDBC.ConnectionFactory;
import Model.Sessao;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinícius Mardegan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        configurarAcessos();
    }

    private void mostrarTela(javax.swing.JPanel novaTela) {
        painelConteudo.removeAll();

        // Força o painel a usar BorderLayout para expandir o conteúdo 100%
        painelConteudo.setLayout(new java.awt.BorderLayout());
        painelConteudo.add(novaTela, java.awt.BorderLayout.CENTER);

        painelConteudo.revalidate();
        painelConteudo.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelConteudo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoJogadores = new javax.swing.JButton();
        botaoClubes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botaoReceitas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botaoDashboard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botaoDespesa1 = new javax.swing.JButton();
        botaoRelatorio = new javax.swing.JButton();
        botaoPartida = new javax.swing.JButton();
        botaoRelatorioDesempenho = new javax.swing.JButton();
        botaoAuditoria = new javax.swing.JButton();
        botaoUsuarios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelConteudo.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("tela Principal");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout painelConteudoLayout = new javax.swing.GroupLayout(painelConteudo);
        painelConteudo.setLayout(painelConteudoLayout);
        painelConteudoLayout.setHorizontalGroup(
                painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelConteudoLayout.createSequentialGroup()
                                .addGap(412, 412, 412)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(480, Short.MAX_VALUE)));
        painelConteudoLayout.setVerticalGroup(
                painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelConteudoLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(120, 120, 120));

        jLabel2.setText("OPERAÇÕES");

        botaoJogadores.setBackground(new java.awt.Color(120, 120, 120));
        botaoJogadores.setText("Jogadores");
        botaoJogadores.setAlignmentY(0.0F);
        botaoJogadores.setBorderPainted(false);
        botaoJogadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoJogadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoJogadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoJogadoresMouseEntered(evt);
            }
        });
        botaoJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogadoresActionPerformed(evt);
            }
        });

        botaoClubes.setBackground(new java.awt.Color(120, 120, 120));
        botaoClubes.setText("Clube");
        botaoClubes.setAlignmentY(0.0F);
        botaoClubes.setBorderPainted(false);
        botaoClubes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoClubes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoClubes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoClubesMouseEntered(evt);
            }
        });
        botaoClubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClubesActionPerformed(evt);
            }
        });

        jLabel3.setText("ADMINISTRAÇÃO");

        botaoReceitas.setBackground(new java.awt.Color(120, 120, 120));
        botaoReceitas.setText("Receitas");
        botaoReceitas.setAlignmentY(0.0F);
        botaoReceitas.setBorderPainted(false);
        botaoReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoReceitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoReceitasMouseEntered(evt);
            }
        });
        botaoReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReceitasActionPerformed(evt);
            }
        });

        jLabel4.setText("GERAL");

        botaoDashboard.setBackground(new java.awt.Color(120, 120, 120));
        botaoDashboard.setText("Dashboard");
        botaoDashboard.setAlignmentY(0.0F);
        botaoDashboard.setBorderPainted(false);
        botaoDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDashboardMouseEntered(evt);
            }
        });
        botaoDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDashboardActionPerformed(evt);
            }
        });

        jLabel5.setText("ANÁLISE");

        botaoDespesa1.setBackground(new java.awt.Color(120, 120, 120));
        botaoDespesa1.setText("Despesas");
        botaoDespesa1.setAlignmentY(0.0F);
        botaoDespesa1.setBorderPainted(false);
        botaoDespesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoDespesa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoDespesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDespesa1MouseEntered(evt);
            }
        });
        botaoDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDespesa1ActionPerformed(evt);
            }
        });

        botaoRelatorio.setBackground(new java.awt.Color(120, 120, 120));
        botaoRelatorio.setText("Relatório Financeiro");
        botaoRelatorio.setAlignmentY(0.0F);
        botaoRelatorio.setBorderPainted(false);
        botaoRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRelatorioMouseEntered(evt);
            }
        });
        botaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioActionPerformed(evt);
            }
        });

        botaoPartida.setBackground(new java.awt.Color(120, 120, 120));
        botaoPartida.setText("Partidas");
        botaoPartida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPartidaMouseEntered(evt);
            }
        });
        botaoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPartidaActionPerformed(evt);
            }
        });

        botaoRelatorioDesempenho.setBackground(new java.awt.Color(120, 120, 120));
        botaoRelatorioDesempenho.setText("Relatório Desempenho");
        botaoRelatorioDesempenho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoRelatorioDesempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioDesempenhoActionPerformed(evt);
            }
        });

        botaoAuditoria.setBackground(new java.awt.Color(120, 120, 120));
        botaoAuditoria.setText("Auditoria");
        botaoAuditoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAuditoriaActionPerformed(evt);
            }
        });

        botaoUsuarios.setBackground(new java.awt.Color(120, 120, 120));
        botaoUsuarios.setText("Usuários");
        botaoUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(botaoClubes, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(botaoDashboard, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(botaoPartida, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(botaoDespesa1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoReceitas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(botaoAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(botaoJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(botaoRelatorioDesempenho,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoRelatorio, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(81, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRelatorioDesempenho, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE)));

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sistema SAF");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("root | Administrador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(botaoSair)
                                .addGap(29, 29, 29)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, 43,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(painelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(painelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja sair da Sessão?", "Encerrar Sessão",
                JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            Sessao.encerrarSessao();
            View.Usuario.TelaAutenticacaoUsuario telaAutenticacaoUsuario = new View.Usuario.TelaAutenticacaoUsuario();
            this.setContentPane(telaAutenticacaoUsuario);
            this.revalidate();
            this.repaint();

            return;
        }
    }// GEN-LAST:event_botaoSairActionPerformed

    private void botaoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoUsuariosActionPerformed
        View.Usuario.TelaUsuario telaUsuarios = new View.Usuario.TelaUsuario();
        mostrarTela(telaUsuarios);
    }// GEN-LAST:event_botaoUsuariosActionPerformed

    private void botaoAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoAuditoriaActionPerformed
        View.Auditoria.TelaAuditoria telaAuditoria = new View.Auditoria.TelaAuditoria();
        mostrarTela(telaAuditoria);
    }// GEN-LAST:event_botaoAuditoriaActionPerformed

    private void botaoDashboardMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoDashboardMouseEntered
        botaoDashboard.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoDashboardMouseEntered

    private void botaoDashboardActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoDashboardActionPerformed
        View.TelaDashboard telaDashboard = new View.TelaDashboard();

        telaDashboard.atualizarConteudo();
        mostrarTela(telaDashboard);
    }// GEN-LAST:event_botaoDashboardActionPerformed

    private void botaoDespesa1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoDespesa1MouseEntered
        botaoDespesa1.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoDespesa1MouseEntered

    private void botaoDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoDespesa1ActionPerformed
        View.Despesa.TelaDespesa telaDespesa = new View.Despesa.TelaDespesa();
        mostrarTela(telaDespesa);
    }// GEN-LAST:event_botaoDespesa1ActionPerformed

    private void botaoRelatorioMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoRelatorioMouseEntered
        botaoRelatorio.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoRelatorioMouseEntered

    private void botaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoRelatorioActionPerformed
        View.Relatorio.TelaRelatorioFinanceiro telaRelatorioFinanceiro = new View.Relatorio.TelaRelatorioFinanceiro();
        mostrarTela(telaRelatorioFinanceiro);
    }// GEN-LAST:event_botaoRelatorioActionPerformed

    private void botaoPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoPartidaActionPerformed
        View.Partida.TelaPartida telaPartida = new View.Partida.TelaPartida();
        mostrarTela(telaPartida);
    }// GEN-LAST:event_botaoPartidaActionPerformed

    private void botaoPartidaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoPartidaMouseEntered
        botaoPartida.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoPartidaMouseEntered

    private void botaoRelatorioDesempenhoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoRelatorioDesempenhoActionPerformed
        View.Relatorio.TelaRelatorioDesempenho telaRelatorioDesempenho = new View.Relatorio.TelaRelatorioDesempenho();
        mostrarTela(telaRelatorioDesempenho);
    }// GEN-LAST:event_botaoRelatorioDesempenhoActionPerformed

    private void botaoJogadoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoJogadoresActionPerformed
        View.Jogador.TelaJogador telaJogador = new View.Jogador.TelaJogador();

        mostrarTela(telaJogador);
    }// GEN-LAST:event_botaoJogadoresActionPerformed

    private void botaoJogadoresMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoJogadoresMouseEntered
        botaoJogadores.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoJogadoresMouseEntered

    private void botaoClubesMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoClubesMouseEntered
        botaoClubes.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoClubesMouseEntered

    private void botaoClubesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoClubesActionPerformed
        View.Clube.TelaClube telaClube = new View.Clube.TelaClube();

        mostrarTela(telaClube);
    }// GEN-LAST:event_botaoClubesActionPerformed

    private void botaoReceitasMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoReceitasMouseEntered
        botaoReceitas.setBackground(new java.awt.Color(80, 80, 80));
    }// GEN-LAST:event_botaoReceitasMouseEntered

    private void botaoReceitasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoReceitasActionPerformed
        View.Receita.TelaReceita telaReceita = new View.Receita.TelaReceita();

        mostrarTela(telaReceita);
    }// GEN-LAST:event_botaoReceitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBC.ConnectionFactory.iniciarTabelaClube();
                JDBC.ConnectionFactory.iniciarTabelaTransacao();
                JDBC.ConnectionFactory.iniciarTabelaUsuario();
                JDBC.ConnectionFactory.iniciarTabelaJogador();
                JDBC.ConnectionFactory.iniciarTabelaPartida();
                JDBC.ConnectionFactory.iniciarTabelaAuditoria();

                TelaPrincipal tela = new TelaPrincipal();
                // se nao existir usuario cadastrado no banco de dados, abre a telka de primeiro
                // cadastro (de ADM)
                if (UsuarioDAO.existeUsuarioCadastrado() == false) {
                    tela.setContentPane(new TelaCadastroADM());
                } else {
                    tela.setContentPane(new TelaAutenticacaoUsuario());
                }

                tela.revalidate();
                tela.repaint();
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAuditoria;
    private javax.swing.JButton botaoClubes;
    private javax.swing.JButton botaoDashboard;
    private javax.swing.JButton botaoDespesa1;
    private javax.swing.JButton botaoJogadores;
    private javax.swing.JButton botaoPartida;
    private javax.swing.JButton botaoReceitas;
    private javax.swing.JButton botaoRelatorio;
    private javax.swing.JButton botaoRelatorioDesempenho;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelConteudo;
    // End of variables declaration//GEN-END:variables

    private void configurarAcessos() {
        // Se ainda não há usuário logado (ex: abrindo tela de login), não faz nada
        if (Model.Sessao.getUsuarioLogado() == null) {
            return;
        }

        int nivel = Model.Sessao.getUsuarioLogado().getNivel_usuario();

        // 0 = Administrador (tem acesso a tudo)
        // 1 = Gestor Financeiro
        // 2 = Operador

        if (nivel == 1) { // Gestor Financeiro
            botaoClubes.setEnabled(false);
            botaoPartida.setEnabled(false);
            botaoRelatorioDesempenho.setEnabled(false);
            botaoAuditoria.setEnabled(false);
        } else if (nivel == 2) { // Operador
            botaoClubes.setEnabled(false);
            botaoJogadores.setEnabled(false);
            botaoDespesa1.setEnabled(false);
            botaoReceitas.setEnabled(false);
            botaoRelatorio.setEnabled(false);
            botaoAuditoria.setEnabled(false);
        }
    }
}
