/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControladorUsuario;

/**
 *
 * @author Vinícius Mardegan
 */
public class TelaCadastroUsuario extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
    }
    
    /**
     * Método main temporário para testar o JPanel isoladamente.
     */
    public static void main(String args[]) {
        /* Cria e exibe o JFrame que conterá o painel de teste */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Testando Tela de Cadastro de Usuário");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                
                // Instancia o seu painel
                TelaCadastroUsuario painelCadastro = new TelaCadastroUsuario();
                
                // Limpa o texto padrão do campo de senha para o teste ficar melhor
                painelCadastro.campoSenha.setText("");
                
                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelCadastro);
                
                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }
    
    public void cadastrarUsuario() {
        String nome_usuario;
        String senha;
        int nivel_usuario;
        ControladorUsuario controladorUsuario = new ControladorUsuario();
        
        nome_usuario = campoNomeUsuario.getText();
        senha = new String(campoSenha.getPassword());
        nivel_usuario = campoNivelUsuario.getSelectedIndex();
        
        boolean operacaoConcluida = controladorUsuario.cadastrarUsuario(nome_usuario, senha, nivel_usuario);
        if (operacaoConcluida == false) {
            exibirMensagemInvalido();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNivelUsuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome de Usuário");

        campoNomeUsuario.setBackground(new java.awt.Color(200, 200, 200));
        campoNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha");

        campoNivelUsuario.setBackground(new java.awt.Color(220, 220, 220));
        campoNivelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoNivelUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador (ADM)", "Gestor Financeiro (GF)", "Operador (OP)" }));
        campoNivelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNivelUsuarioActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoSenha.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNivelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, 0, 157, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(campoNomeUsuario)
                            .addComponent(jLabel2)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoSenha))))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoNivelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrarUsuario();
    
        // Descobre qual é o JFrame que está segurando este JPanel
        javax.swing.JFrame framePai = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        if (framePai instanceof TelaPrincipal telaPrincipal) {

            // Cria uma nova instância limpa da TelaPrincipal para resetar o layout original
            framePai.dispose(); // Fecha a janela atual
            new TelaPrincipal().setVisible(true); // Abre uma nova, que agora vai cair no "existeUsuarioCadastrado() == true"
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoNivelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNivelUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNivelUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campoNivelUsuario;
    private javax.swing.JTextField campoNomeUsuario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void exibirMensagemInvalido() {
        javax.swing.JOptionPane.showMessageDialog(
                null,
                "Nome de usuário ou senha inválidos.",
                "Erro de autenticação",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
    }
}
