/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControladorFinanceiro;
import JDBC.ConnectionFactory;
import Model.Receita;
import Model.TransacaoFinanceira;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaReceita extends javax.swing.JPanel {

    /**
     * Creates new form TelaTransacao
     */
    public TelaReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarReceita = new javax.swing.JButton();
        jButton2ListarReceitas = new javax.swing.JButton();
        jButton3EditarReceita = new javax.swing.JButton();
        jButton4BuscarReceita = new javax.swing.JButton();
        jButton5ExcluirReceita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReceitas = new javax.swing.JTable();

        jButtonCadastrarReceita.setText("Cadastrar Receita");
        jButtonCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarReceitaActionPerformed(evt);
            }
        });

        jButton2ListarReceitas.setText("Listar Receitas");
        jButton2ListarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ListarReceitasActionPerformed(evt);
            }
        });

        jButton3EditarReceita.setText("Editar Receita");
        jButton3EditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EditarReceitaActionPerformed(evt);
            }
        });

        jButton4BuscarReceita.setText("Buscar Receita");
        jButton4BuscarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4BuscarReceitaActionPerformed(evt);
            }
        });

        jButton5ExcluirReceita.setText("Excluir Receita");
        jButton5ExcluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirReceitaActionPerformed(evt);
            }
        });

        tabelaReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "descrição", "categoria", "valor", "data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaReceitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaReceitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarReceita)
                        .addGap(80, 80, 80)
                        .addComponent(jButton2ListarReceitas)
                        .addGap(62, 62, 62)
                        .addComponent(jButton3EditarReceita)
                        .addGap(83, 83, 83)
                        .addComponent(jButton4BuscarReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButton5ExcluirReceita)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2ListarReceitas)
                    .addComponent(jButton3EditarReceita)
                    .addComponent(jButton4BuscarReceita)
                    .addComponent(jButton5ExcluirReceita)
                    .addComponent(jButtonCadastrarReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarReceitaActionPerformed

        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaCadastroReceita telaCadastro = new TelaCadastroReceita(framePai, true);

        telaCadastro.setVisible(true);

    }//GEN-LAST:event_jButtonCadastrarReceitaActionPerformed

    
    private void jButton2ListarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ListarReceitasActionPerformed
        
        
        ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

        ConnectionFactory.iniciarTabelaTransacao();

        DefaultTableModel modelo = (DefaultTableModel) tabelaReceitas.getModel();

        modelo.setNumRows(0);

        ArrayList<TransacaoFinanceira> receitas = controladorFinanceiro.iniciarListagemDeReceitas();

        for (TransacaoFinanceira r : receitas) {

            Object[] linha = {
                r.getIdTransacao(),
                r.getDescricao(),
                r.getCategoria(),
                r.getValor(),
                r.getData()
            };

            modelo.addRow(linha);

        }
                
    }//GEN-LAST:event_jButton2ListarReceitasActionPerformed

    private void jButton3EditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EditarReceitaActionPerformed

        int linhaSelecionada = tabelaReceitas.getSelectedRow();

        if (linhaSelecionada != -1){
            try {
                Object valorId = tabelaReceitas.getValueAt(linhaSelecionada, 0);

                int id = Integer.parseInt(tabelaReceitas.getValueAt(linhaSelecionada, 0).toString());
                String descricao = tabelaReceitas.getValueAt(linhaSelecionada, 1).toString();
                String categoria = tabelaReceitas.getValueAt(linhaSelecionada, 2).toString();
                float valor = Float.parseFloat(tabelaReceitas.getValueAt(linhaSelecionada, 3).toString());
                
                java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

                TelaAlterarReceita telaAlterarReceita = new TelaAlterarReceita(framePai, true, id, descricao, categoria, valor);

                telaAlterarReceita.setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }//GEN-LAST:event_jButton3EditarReceitaActionPerformed

    private void jButton4BuscarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4BuscarReceitaActionPerformed
        try {
            int idReceita = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "ID da receita:"));

            ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

            ConnectionFactory.iniciarTabelaTransacao();

            TransacaoFinanceira r = controladorFinanceiro.iniciarBuscaDeReceitas(idReceita);

            DefaultTableModel modelo = (DefaultTableModel) tabelaReceitas.getModel();

            modelo.setNumRows(0);

            Object[] linha = {
                r.getIdTransacao(),
                r.getDescricao(),
                r.getCategoria(),
                r.getValor(),
                r.getData()
            };

            modelo.addRow(linha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Receita não encontrada ou Operação cancelada");
        }


        
    }//GEN-LAST:event_jButton4BuscarReceitaActionPerformed

    private void jButton5ExcluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExcluirReceitaActionPerformed

        int linhaSelecionada = tabelaReceitas.getSelectedRow();

        if (linhaSelecionada != -1){
            try {
                Object valorId = tabelaReceitas.getValueAt(linhaSelecionada, 0);

                int idTransacao = Integer.parseInt(tabelaReceitas.getValueAt(linhaSelecionada, 0).toString());
                
                float valor = Float.parseFloat(tabelaReceitas.getValueAt(linhaSelecionada, 3).toString());

                
                int resposta = JOptionPane.showConfirmDialog(
                    null, 
                    "O saldo do clube será subtraído por " + valor, 
                    "Confirmar Exclusão de Receita", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE
                );
                
                
                if (resposta == JOptionPane.YES_OPTION){
                    ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();

                    ConnectionFactory.iniciarTabelaTransacao();
                    
                    // ALTERAR ISSO AQUI QUANDO DER
                    int idClube = 0;

                    controladorFinanceiro.iniciarExclusaoDeReceita(idTransacao, idClube);
                }
                else {
                    return;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

        

    }//GEN-LAST:event_jButton5ExcluirReceitaActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Tela de Receita");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel
                TelaReceita painelTransacao = new TelaReceita();

                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelTransacao);

                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2ListarReceitas;
    private javax.swing.JButton jButton3EditarReceita;
    private javax.swing.JButton jButton4BuscarReceita;
    private javax.swing.JButton jButton5ExcluirReceita;
    private javax.swing.JButton jButtonCadastrarReceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaReceitas;
    // End of variables declaration//GEN-END:variables
}
