/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControladorClube;
import JDBC.ConnectionFactory;
import Model.Clube;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaClube extends javax.swing.JPanel {

    /**
     * Creates new form TelaClube
     */
    public TelaClube() {
        initComponents();
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Tela de Clube");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel
                TelaClube painelClube = new TelaClube();

                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelClube);

                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarClube = new javax.swing.JButton();
        jButton2ListarClubes = new javax.swing.JButton();
        jButton3EditarClube = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5ExcluirClube = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClubes = new javax.swing.JTable();

        jButtonCadastrarClube.setText("Cadastrar Clube");
        jButtonCadastrarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClubeActionPerformed(evt);
            }
        });

        jButton2ListarClubes.setText("Listar Clubes");
        jButton2ListarClubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ListarClubesActionPerformed(evt);
            }
        });

        jButton3EditarClube.setText("Editar Clube");
        jButton3EditarClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EditarClubeActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar Clube");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5ExcluirClube.setText("Excluir Clube");
        jButton5ExcluirClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirClubeActionPerformed(evt);
            }
        });

        tabelaClubes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nome", "ano de fundação", "país"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClubes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaClubes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarClube)
                        .addGap(60, 60, 60)
                        .addComponent(jButton2ListarClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3EditarClube, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton5ExcluirClube, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2ListarClubes)
                    .addComponent(jButton3EditarClube)
                    .addComponent(jButton4)
                    .addComponent(jButton5ExcluirClube)
                    .addComponent(jButtonCadastrarClube))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClubeActionPerformed
        
        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        TelaCadastroClube telaCadastro = new TelaCadastroClube(framePai, true);
        
        telaCadastro.setVisible(true);  

        
    }//GEN-LAST:event_jButtonCadastrarClubeActionPerformed

    private void jButton2ListarClubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ListarClubesActionPerformed
        ControladorClube controladorClube = new ControladorClube();
        
        ConnectionFactory.iniciarTabelaClube();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaClubes.getModel();
        
        modelo.setNumRows(0);
        
        ArrayList<Clube> clubes = controladorClube.listarClubes();
        
        for (Clube clube : clubes) {
            
            
            Object[] linha = {
                clube.getIdClube(),
                clube.getNome(),
                clube.getAnoDeFundacao(),
                clube.getPais()
            };
            
            
        modelo.addRow(linha);
        
        }
    }//GEN-LAST:event_jButton2ListarClubesActionPerformed

    private void jButton3EditarClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EditarClubeActionPerformed
        
        int linhaSelecionada = tabelaClubes.getSelectedRow();

        if (linhaSelecionada != -1){
            try {
                Object valorId = tabelaClubes.getValueAt(linhaSelecionada, 0);
        
                int id = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 0).toString());
                String nome = tabelaClubes.getValueAt(linhaSelecionada, 1).toString();
                int anoFundacao = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 2).toString());
                String pais = tabelaClubes.getValueAt(linhaSelecionada, 3).toString();
                
                java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
                TelaAlterarClube telaAlterarClube = new TelaAlterarClube(framePai, true, id, nome, anoFundacao, pais);
               
                telaAlterarClube.setVisible(true); 
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }
        
    }//GEN-LAST:event_jButton3EditarClubeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            int idClube = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "ID do clube:"));
        
            ControladorClube controladorClube = new ControladorClube();
            
            ConnectionFactory.iniciarTabelaClube();


            Clube c = controladorClube.buscarClube(idClube);

            DefaultTableModel modelo = (DefaultTableModel) tabelaClubes.getModel();

            modelo.setNumRows(0);

            Object[] linha = {
                    c.getIdClube(),
                    c.getNome(),
                    c.getAnoDeFundacao(),
                    c.getPais()
                };


            modelo.addRow(linha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clube não encontrado ou Operação cancelada");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ExcluirClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExcluirClubeActionPerformed
        
        
        int linhaSelecionada = tabelaClubes.getSelectedRow();

        if (linhaSelecionada != -1){
            try {
                Object valorId = tabelaClubes.getValueAt(linhaSelecionada, 0);
        
                int id = Integer.parseInt(tabelaClubes.getValueAt(linhaSelecionada, 0).toString());
                
                ControladorClube controladorClube = new ControladorClube();
            
                ConnectionFactory.iniciarTabelaClube();
                
                controladorClube.iniciarExclusaoDeClube(id);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }
        
        
        
    }//GEN-LAST:event_jButton5ExcluirClubeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2ListarClubes;
    private javax.swing.JButton jButton3EditarClube;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5ExcluirClube;
    private javax.swing.JButton jButtonCadastrarClube;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClubes;
    // End of variables declaration//GEN-END:variables
}
