/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.util.List;
import java.util.Arrays;
import javax.swing.JCheckBox;

/**
 *
 * @author Cauan
 */
public class TelaRelatorioFinanceiro extends javax.swing.JPanel {

    private List<JCheckBox> listaReceitas;
    private List<JCheckBox> listaDespesas;
    
    /**
     * Creates new form TelaRelatorioFinanceiro
     */
    public TelaRelatorioFinanceiro() {
           
        initComponents();
        
        listaReceitas = Arrays.asList(chkBilheteria, chkPatrocinio, chkProdutos, chkSocio, chkPremiacoes);
        listaDespesas = Arrays.asList(chkInfraestrutura, chkProducao, chkSaude, chkSalarios, chkViagens);

        jComboBox1Tipo.addActionListener(e -> gerenciarFiltrosEmTela());
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Tela de Relatório Financeiro");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel
                TelaRelatorioFinanceiro painelFinanceiro = new TelaRelatorioFinanceiro();

                // Coloca o painel dentro do JFrame de teste
                frameTeste.setContentPane(painelFinanceiro);

                // Ajusta o tamanho da janela e centraliza na tela
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1Tipo = new javax.swing.JComboBox<>();
        chkBilheteria = new javax.swing.JCheckBox();
        chkPatrocinio = new javax.swing.JCheckBox();
        chkProdutos = new javax.swing.JCheckBox();
        chkSocio = new javax.swing.JCheckBox();
        chkPremiacoes = new javax.swing.JCheckBox();
        chkOutras = new javax.swing.JCheckBox();
        chkInfraestrutura = new javax.swing.JCheckBox();
        chkProducao = new javax.swing.JCheckBox();
        chkSaude = new javax.swing.JCheckBox();
        chkSalarios = new javax.swing.JCheckBox();
        chkViagens = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jComboBox1Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Receita", "Despesa" }));

        chkBilheteria.setText("Bilheteria");
        chkBilheteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBilheteriaActionPerformed(evt);
            }
        });

        chkPatrocinio.setText("Patrocínio");

        chkProdutos.setText("Produtos");

        chkSocio.setText("Plano sócio-torcedor");

        chkPremiacoes.setText("Premiações");

        chkOutras.setText("Outras");

        chkInfraestrutura.setText("Infraestrutura");

        chkProducao.setText("Produção");

        chkSaude.setText("Saúde e Fisioterapia");

        chkSalarios.setText("Salários e Encargos");

        chkViagens.setText("Viagens e Lógisticas");
        chkViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViagensActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkProdutos)
                    .addComponent(chkSocio)
                    .addComponent(chkPatrocinio)
                    .addComponent(chkPremiacoes)
                    .addComponent(chkBilheteria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkInfraestrutura)
                    .addComponent(chkProducao)
                    .addComponent(chkSaude)
                    .addComponent(chkSalarios)
                    .addComponent(chkViagens))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(chkOutras))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkInfraestrutura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkProducao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSaude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSalarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkViagens))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBilheteria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPatrocinio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPremiacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(chkOutras)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkBilheteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBilheteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBilheteriaActionPerformed

    private void chkViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkViagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkViagensActionPerformed

    private void gerenciarFiltrosEmTela() {
     
    
    String opcaoSelecionada = (String) jComboBox1Tipo.getSelectedItem();

    if ("Geral".equals(opcaoSelecionada)) {
        // Opção Geral: Habilita absolutamente tudo
        listaReceitas.forEach(chk -> chk.setEnabled(true));
        listaDespesas.forEach(chk -> chk.setEnabled(true));
        chkOutras.setEnabled(true);
    } 
    else if ("Receita".equals(opcaoSelecionada)) {
        // Opção Receita: Liga receitas, desliga e limpa despesas
        listaReceitas.forEach(chk -> chk.setEnabled(true));
        listaDespesas.forEach(chk -> {
            chk.setEnabled(false);
            chk.setSelected(false); // limpa a seleção para não enviar lixo no relatório
        });
        chkOutras.setEnabled(true);
    } 
    else if ("Despesa".equals(opcaoSelecionada)) {
        // Opção Despesa: Liga despesas, desliga e limpa receitas
        listaDespesas.forEach(chk -> chk.setEnabled(true));
        listaReceitas.forEach(chk -> {
            chk.setEnabled(false);
            chk.setSelected(false);
        });
        chkOutras.setEnabled(true);
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBilheteria;
    private javax.swing.JCheckBox chkInfraestrutura;
    private javax.swing.JCheckBox chkOutras;
    private javax.swing.JCheckBox chkPatrocinio;
    private javax.swing.JCheckBox chkPremiacoes;
    private javax.swing.JCheckBox chkProducao;
    private javax.swing.JCheckBox chkProdutos;
    private javax.swing.JCheckBox chkSalarios;
    private javax.swing.JCheckBox chkSaude;
    private javax.swing.JCheckBox chkSocio;
    private javax.swing.JCheckBox chkViagens;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1Tipo;
    // End of variables declaration//GEN-END:variables
}
