/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControladorFinanceiro;
import Controller.ControladorJogador;
import Controller.ControladorPartida;
import Model.Jogador;
import Model.Partida;
import Model.Receita;
import Model.TransacaoFinanceira;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaDashboard extends javax.swing.JPanel {

    /**
     * Creates new form TelaDashboard
     */
    public TelaDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textReceitasTotais = new javax.swing.JTextField();
        textDespesasTotais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textPartidasJogadas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textSaldoAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textJogadoresElenco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDashboard = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Receitas Totais");

        textReceitasTotais.setEditable(false);

        textDespesasTotais.setEditable(false);

        jLabel2.setText("Despesas Totais");

        textPartidasJogadas.setEditable(false);

        jLabel3.setText("Saldo Atual");

        jLabel4.setText("Jogadores no Elenco");

        textSaldoAtual.setEditable(false);

        jLabel5.setText("Partidas jogadas");

        textJogadoresElenco.setEditable(false);

        jLabel6.setText("Dashboard");

        jTableDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Descrição", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDashboard);

        jLabel7.setText("Lançamentos Recentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textReceitasTotais))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textDespesasTotais))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textSaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textJogadoresElenco))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textPartidasJogadas)))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPartidasJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textJogadoresElenco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textReceitasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDespesasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarConteudo(){
        
        ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();
        ControladorJogador controladorJogador = new ControladorJogador();
        ControladorPartida controladorPartida = new ControladorPartida();
        
        ArrayList<TransacaoFinanceira> receitas = controladorFinanceiro.iniciarListagemDeReceitas();
        ArrayList<TransacaoFinanceira> despesas = controladorFinanceiro.iniciarListagemDeDespesas();
        
        // alterar quando Partida estiver implementado!
        ArrayList<Jogador> jogadores = null;
        //ArrayList<Jogador> jogadores = controladorJogador.iniciarListagemDeJogador();
        
        // alterar quando Partida estiver implementado!
        ArrayList<Partida> partidas = null;
        //ArrayList<Partida> partidas = controladorPartida.
        
        float valorTotalReceita = 0;
        float valorTotalDespesa = 0;
        
        for (TransacaoFinanceira r: receitas){
            valorTotalReceita += r.getValor();
        }
        
        for (TransacaoFinanceira d: despesas){
            valorTotalDespesa += d.getValor();
        }
        
        textReceitasTotais.setText(Float.toString(valorTotalReceita));
        textDespesasTotais.setText(Float.toString(valorTotalDespesa));
        textSaldoAtual.setText(Float.toString(valorTotalReceita - valorTotalDespesa));
        
        // TROCAR AQUI
        textJogadoresElenco.setText(Integer.toString(0));
        
        // TROCAR AQUI
        textPartidasJogadas.setText(Integer.toString(0));
        
        
        receitas.sort(Comparator.comparing(TransacaoFinanceira::getData).reversed());
        despesas.sort(Comparator.comparing(TransacaoFinanceira::getData).reversed());
        //jogadores.reversed();
        //partidas.reversed();
        
        
        TransacaoFinanceira ultimaReceita = !receitas.isEmpty() ? receitas.get(0) : null;
        TransacaoFinanceira ultimaDespesa = !despesas.isEmpty() ? despesas.get(0) : null;
        //Jogador ultimoJogador = !jogadores.isEmpty() ? jogadores.get(0) : null;
        //Partida ultimaPartida = !partidas.isEmpty() ? partidas.get(0) : null;

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        Object[][] dadosTabela = {
            {
                "Receita",
                ultimaReceita != null ? ultimaReceita.getDescricao() : "Nenhuma",
                ultimaReceita != null ? ultimaReceita.getValor() : 0.0,
                ultimaReceita != null ? sdf.format(ultimaReceita.getData()) : "-"
            },
            {
                "Despesa",
                ultimaDespesa != null ? ultimaDespesa.getDescricao() : "Nenhuma",
                ultimaDespesa != null ? ultimaDespesa.getValor() : 0.0,
                ultimaDespesa != null ? sdf.format(ultimaDespesa.getData()) : "-"
            },
            {
                "Jogador",
                //ultimoJogador != null ? ultimoJogador.getNome() : "Nenhum",
                "-", 
                "-"
            },
            {
                "Partida",
                //ultimaPartida != null ? ultimaPartida.getLocal(): "Nenhuma",
                //ultimaPartida != null ? ultimaPartida.getPremiacao(): 0.0,
                //ultimaPartida != null ? sdf.format(ultimaPartida.getData()) : "-"
            }
        };
        
        String[] colunas = {"Tipo", "Descrição", "Valor", "Data"};

        
        DefaultTableModel modelo = new DefaultTableModel(dadosTabela, colunas);
        jTableDashboard.setModel(modelo);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDashboard;
    private javax.swing.JTextField textDespesasTotais;
    private javax.swing.JTextField textJogadoresElenco;
    private javax.swing.JTextField textPartidasJogadas;
    private javax.swing.JTextField textReceitasTotais;
    private javax.swing.JTextField textSaldoAtual;
    // End of variables declaration//GEN-END:variables
}
