/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControladorFinanceiro;
import Controller.ControladorJogador;
import Controller.ControladorPartida;
import Model.Jogador.Jogador;
import Model.Partida.Partida;
import Model.TransacaoFinanceira.TransacaoFinanceira.*;
import Model.TransacaoFinanceira.TransacaoFinanceira;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauan
 */
public class TelaDashboard extends javax.swing.JPanel {

        // Labels de valor dos cards (atualizados em atualizarConteudo)
        private JLabel lblReceitasValor;
        private JLabel lblDespesasValor;
        private JLabel lblSaldoValor;
        private JLabel lblJogadoresValor;
        private JLabel lblPartidasValor;

        /**
         * Creates new form TelaDashboard
         */
        public TelaDashboard() {
                initComponents();
                customizarLayout();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                textReceitasTotais = new javax.swing.JTextField();
                textDespesasTotais = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                textPartidasJogadas = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                textSaldoAtual = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                textJogadoresElenco = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTableDashboard = new javax.swing.JTable();
                jLabel7 = new javax.swing.JLabel();

                jLabel1.setText("Receitas Totais");

                textReceitasTotais.setEditable(false);

                textDespesasTotais.setEditable(false);

                jLabel2.setText("Despesas Totais");

                textPartidasJogadas.setEditable(false);

                jLabel3.setText("Saldo Atual");

                jLabel4.setText("Jogadores no Elenco");

                textSaldoAtual.setEditable(false);

                jLabel5.setText("Partidas jogadas");

                textJogadoresElenco.setEditable(false);

                jLabel6.setText("Dashboard");

                jTableDashboard.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Tipo", "Descrição", "Valor", "Data"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(jTableDashboard);

                jLabel7.setText("Lançamentos Recentes");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jScrollPane1)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textReceitasTotais))
                                                                                                                .addGap(55, 55, 55)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textDespesasTotais))
                                                                                                                .addGap(47, 47, 47)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(textSaldoAtual,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                94,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addGap(30, 30, 30)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(textJogadoresElenco))
                                                                                                                                                .addGap(47, 47, 47)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(textPartidasJogadas)))
                                                                                                                                .addComponent(jLabel6,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                138,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                160,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(90, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(jLabel6)
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel5))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(textSaldoAtual,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textPartidasJogadas,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textJogadoresElenco,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addComponent(jLabel2)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(textReceitasTotais,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(textDespesasTotais,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                64,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(400, 400, 400)));
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Substitui o layout gerado pelo NetBeans por cards estilizados.
         */
        private void customizarLayout() {
                removeAll();
                setLayout(new BorderLayout(24, 24));
                setBackground(Theme.BACKGROUND);
                setBorder(new EmptyBorder(40, 40, 40, 40));

                // ===== HEADER =====
                JPanel headerPanel = new JPanel();
                headerPanel.setLayout(new BoxLayout(headerPanel, BoxLayout.Y_AXIS));
                headerPanel.setBackground(Theme.BACKGROUND);

                JLabel lblTitulo = new JLabel("Dashboard");
                lblTitulo.setFont(Theme.FONT_TITLE);
                lblTitulo.setForeground(Theme.CINZA_ESCURO);

                JLabel lblSubtitulo = new JLabel("Resumo financeiro e operacional do clube");
                lblSubtitulo.setFont(Theme.FONT_SUBTITLE);
                lblSubtitulo.setForeground(Theme.CINZA_CLARO);

                headerPanel.add(lblTitulo);
                headerPanel.add(Box.createVerticalStrut(8));
                headerPanel.add(lblSubtitulo);

                add(headerPanel, BorderLayout.NORTH);

                // ===== CENTRO: Cards + Tabela =====
                JPanel centerPanel = new JPanel();
                centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
                centerPanel.setBackground(Theme.BACKGROUND);

                // --- Linha 1: Receitas, Despesas, Saldo ---
                JPanel cardsFinanceiros = new JPanel(new GridLayout(1, 3, 24, 0));
                cardsFinanceiros.setBackground(Theme.BACKGROUND);
                cardsFinanceiros.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));
                cardsFinanceiros.setAlignmentX(LEFT_ALIGNMENT);

                lblReceitasValor = new JLabel("R$ 0,00");
                lblDespesasValor = new JLabel("R$ 0,00");
                lblSaldoValor = new JLabel("R$ 0,00");

                cardsFinanceiros.add(createCard("Receitas Totais", lblReceitasValor, Theme.VERDE));
                cardsFinanceiros.add(createCard("Despesas Totais", lblDespesasValor, Theme.VERMELHO));
                cardsFinanceiros.add(createCard("Saldo Atual", lblSaldoValor, Theme.COR_PRINCIPAL));

                // --- Linha 2: Jogadores, Partidas ---
                JPanel cardsOperacionais = new JPanel(new GridLayout(1, 3, 24, 0));
                cardsOperacionais.setBackground(Theme.BACKGROUND);
                cardsOperacionais.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));
                cardsOperacionais.setAlignmentX(LEFT_ALIGNMENT);

                lblJogadoresValor = new JLabel("0");
                lblPartidasValor = new JLabel("0");

                cardsOperacionais.add(createCard("Jogadores no Elenco", lblJogadoresValor, Theme.LARANJA));
                cardsOperacionais.add(createCard("Partidas Jogadas", lblPartidasValor, Theme.CINZA));
                JPanel espacoVazio = new JPanel();
                espacoVazio.setBackground(Theme.BACKGROUND);
                cardsOperacionais.add(espacoVazio);

                // --- Tabela de lançamentos recentes ---
                JLabel lblLancamentos = new JLabel("Lançamentos Recentes");
                lblLancamentos.setFont(new Font(Theme.FONT_FAMILY, Font.BOLD, 16));
                lblLancamentos.setForeground(Theme.CINZA_ESCURO);
                lblLancamentos.setAlignmentX(LEFT_ALIGNMENT);

                Theme.styleTable(jTableDashboard);

                JScrollPane scrollPane = new JScrollPane(jTableDashboard);
                scrollPane.getViewport().setBackground(java.awt.Color.WHITE);
                scrollPane.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
                scrollPane.setPreferredSize(new Dimension(Short.MAX_VALUE, 400));
                scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(Theme.CINZA_CLARO_PAINEL, 1));
                scrollPane.setAlignmentX(LEFT_ALIGNMENT);

                // Montagem do centro
                centerPanel.add(cardsFinanceiros);
                centerPanel.add(Box.createVerticalStrut(24));
                centerPanel.add(cardsOperacionais);
                centerPanel.add(Box.createVerticalStrut(32));
                centerPanel.add(lblLancamentos);
                centerPanel.add(Box.createVerticalStrut(12));
                centerPanel.add(scrollPane);

                add(centerPanel, BorderLayout.CENTER);
        }

        /**
         * Cria um card estilizado com título e valor colorido.
         */
        private JPanel createCard(String title, JLabel lblValue, Color color) {
                JPanel card = new JPanel(new BorderLayout());
                card.setBackground(Color.WHITE);
                card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(Theme.CINZA_CLARO_PAINEL, 1),
                                new EmptyBorder(24, 24, 24, 24)));

                JLabel lblTitle = new JLabel(title);
                lblTitle.setFont(Theme.FONT_SUBTITLE);
                lblTitle.setForeground(Theme.CINZA_CLARO);

                lblValue.setFont(new Font(Theme.FONT_FAMILY, Font.BOLD, 28));
                lblValue.setForeground(color);

                card.add(lblTitle, BorderLayout.NORTH);
                card.add(lblValue, BorderLayout.CENTER);

                return card;
        }

        public void atualizarConteudo() {

                ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();
                ControladorJogador controladorJogador = new ControladorJogador();
                ControladorPartida controladorPartida = new ControladorPartida();

                ArrayList<TransacaoFinanceira> receitas = controladorFinanceiro.iniciarListagemDeReceitas();
                ArrayList<TransacaoFinanceira> despesas = controladorFinanceiro.iniciarListagemDeDespesas();
                ArrayList<Jogador> jogadores = controladorJogador.iniciarListagemDeJogador();
                ArrayList<Partida> partidas = controladorPartida.iniciarListagemDePartidas();

                float valorTotalReceita = 0;
                float valorTotalDespesa = 0;

                for (TransacaoFinanceira r : receitas) {
                        valorTotalReceita += r.getValor();
                }

                for (TransacaoFinanceira d : despesas) {
                        valorTotalDespesa += d.getValor();
                }

                // Atualiza os labels dos cards
                lblReceitasValor.setText(String.format("R$ %.2f", valorTotalReceita));
                lblDespesasValor.setText(String.format("R$ %.2f", valorTotalDespesa));

                float saldo = valorTotalReceita - valorTotalDespesa;
                lblSaldoValor.setText(String.format("R$ %.2f", saldo));
                lblSaldoValor.setForeground(saldo >= 0 ? Theme.VERDE : Theme.VERMELHO);

                // TROCAR AQUI
                if (jogadores == null) {
                        lblJogadoresValor.setText("0");
                } else {
                        lblJogadoresValor.setText(Integer.toString(jogadores.size()));
                }

                if (partidas == null) {
                        lblPartidasValor.setText("0");
                } else {
                        lblPartidasValor.setText(Integer.toString(partidas.size()));
                }

                receitas.sort(Comparator.comparing(TransacaoFinanceira::getData).reversed());
                despesas.sort(Comparator.comparing(TransacaoFinanceira::getData).reversed());

                TransacaoFinanceira ultimaReceita = !receitas.isEmpty() ? receitas.get(0) : null;
                TransacaoFinanceira ultimaDespesa = !despesas.isEmpty() ? despesas.get(0) : null;

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                Object[][] dadosTabela = {
                                {
                                                "Receita",
                                                ultimaReceita != null ? ultimaReceita.getDescricao() : "Nenhuma",
                                                ultimaReceita != null
                                                                ? String.format("R$ %.2f", ultimaReceita.getValor())
                                                                : "R$ 0,00",
                                                ultimaReceita != null ? sdf.format(ultimaReceita.getData()) : "-"
                                },
                                {
                                                "Despesa",
                                                ultimaDespesa != null ? ultimaDespesa.getDescricao() : "Nenhuma",
                                                ultimaDespesa != null
                                                                ? String.format("R$ %.2f", ultimaDespesa.getValor())
                                                                : "R$ 0,00",
                                                ultimaDespesa != null ? sdf.format(ultimaDespesa.getData()) : "-"
                                }
                };

                String[] colunas = { "Tipo", "Descrição", "Valor", "Data" };

                DefaultTableModel modelo = new DefaultTableModel(dadosTabela, colunas);
                jTableDashboard.setModel(modelo);
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTableDashboard;
        private javax.swing.JTextField textDespesasTotais;
        private javax.swing.JTextField textJogadoresElenco;
        private javax.swing.JTextField textPartidasJogadas;
        private javax.swing.JTextField textReceitasTotais;
        private javax.swing.JTextField textSaldoAtual;
        // End of variables declaration//GEN-END:variables
}
