/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Usuario;

import Controller.ControladorUsuario;
import View.Clube.TelaCadastroClube;
import View.TelaPrincipal;

/**
 *
 * @author Vinícius Mardegan
 */
public class TelaCadastroADM extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroADM
     */
    public TelaCadastroADM() {
        initComponents();
        aplicarEstilosAdicionais();
    }

    public boolean cadastrarAdministrador() {
        String nome_usuario;
        String senha;
        ControladorUsuario controladorUsuario = new ControladorUsuario();

        nome_usuario = campoNomeUsuario.getText();
        senha = new String(campoSenha.getPassword());

        boolean operacaoConcluida = controladorUsuario.cadastrarUsuario(nome_usuario, senha, 0);
        if (operacaoConcluida == false) {
            exibirMensagemInvalido();
            return false;
        }
        return true;
    }

    public void exibirMensagemInvalido() {
        javax.swing.JOptionPane.showMessageDialog(
                null,
                "Nome de usuário ou senha inválidos.",
                "Erro de autenticação",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Primeiro Administrador");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome de Usuário");

        campoNomeUsuario.setBackground(new java.awt.Color(200, 200, 200));
        campoNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeUsuarioActionPerformed(evt);
            }
        });

        labelSenha.setForeground(new java.awt.Color(0, 0, 0));
        labelSenha.setText("Senha");
        labelSenha.setToolTipText("");

        jButton1.setText("Cadastrar ADM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoSenha.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(301, 301, 301)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(320, 320, 320)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel2)
                                                        .addComponent(campoNomeUsuario)
                                                        .addComponent(labelSenha)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                160, Short.MAX_VALUE)
                                                        .addComponent(campoSenha))))
                                .addContainerGap(308, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap(290, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoNomeUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        if (cadastrarAdministrador()) {
            // Descobre qual é o JFrame que está segurando este JPanel
            javax.swing.JFrame framePai = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

            if (framePai instanceof TelaPrincipal) {
                TelaPrincipal telaPrincipal = (TelaPrincipal) framePai;

                // Abre o dialog do clube logo após cadastrar ADM
                TelaCadastroClube dialogClube = new TelaCadastroClube(telaPrincipal, true);
                dialogClube.setLocationRelativeTo(telaPrincipal);
                dialogClube.setVisible(true); // bloqueia até o usuário fechar

                // Após o cadastro do clube, vai para a tela de login
                telaPrincipal.setContentPane(new TelaAutenticacaoUsuario());
                telaPrincipal.revalidate();
                telaPrincipal.repaint();
            }
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomeUsuario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSenha;
    // End of variables declaration//GEN-END:variables

    private void aplicarEstilosAdicionais() {
        this.removeAll();
        this.setLayout(new java.awt.GridBagLayout());
        this.setBackground(View.Theme.BACKGROUND);

        // painel para o formulario
        javax.swing.JPanel container = new javax.swing.JPanel(new java.awt.GridBagLayout());
        container.setBackground(java.awt.Color.WHITE);
        container.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(View.Theme.CINZA_CLARO_PAINEL, 1),
                new javax.swing.border.EmptyBorder(40, 48, 40, 48)));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(8, 0, 8, 0);
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        gbc.gridx = 0;

        // titulo
        jLabel1.setFont(View.Theme.FONT_TITLE);
        jLabel1.setForeground(View.Theme.CINZA_ESCURO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbc.gridy = 0;
        gbc.insets = new java.awt.Insets(0, 0, 32, 0);
        container.add(jLabel1, gbc);

        gbc.insets = new java.awt.Insets(4, 0, 4, 0);

        // label usuario
        jLabel2.setFont(View.Theme.FONT_TEXT);
        jLabel2.setForeground(View.Theme.CINZA_ESCURO);
        gbc.gridy = 1;
        container.add(jLabel2, gbc);

        // campo usuario
        View.Theme.styleTextField(campoNomeUsuario);
        campoNomeUsuario.setPreferredSize(new java.awt.Dimension(300, 34));
        gbc.gridy = 2;
        gbc.insets = new java.awt.Insets(0, 0, 16, 0);
        container.add(campoNomeUsuario, gbc);

        // label de senha
        labelSenha.setFont(View.Theme.FONT_TEXT);
        labelSenha.setForeground(View.Theme.CINZA_ESCURO);
        gbc.gridy = 3;
        gbc.insets = new java.awt.Insets(4, 0, 4, 0);
        container.add(labelSenha, gbc);

        // campo de senha
        View.Theme.stylePasswordField(campoSenha);
        campoSenha.setPreferredSize(new java.awt.Dimension(300, 34));
        gbc.gridy = 4;
        gbc.insets = new java.awt.Insets(0, 0, 32, 0);
        container.add(campoSenha, gbc);

        // botao de cadastro
        View.Theme.styleButtonPrimary(jButton1);
        jButton1.setPreferredSize(new java.awt.Dimension(300, 36));
        gbc.gridy = 5;
        gbc.insets = new java.awt.Insets(8, 0, 8, 0);
        container.add(jButton1, gbc);

        this.add(container, new java.awt.GridBagConstraints());

        this.revalidate();
        this.repaint();
    }
}
