/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Usuario;

import Controller.ControladorUsuario;
import Model.Sessao;
import View.Clube.TelaEscolherClube;
import View.TelaPrincipal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Vinícius Mardegan
 */
public class TelaAutenticacaoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form TelaAutenticacaoUsuario
     */
    public TelaAutenticacaoUsuario() {
        initComponents();
        aplicarEstilosAdicionais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNomeUsuario = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");

        campoNomeUsuario.setBackground(new java.awt.Color(200, 200, 200));
        campoNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CampoSenha.setBackground(new java.awt.Color(200, 200, 200));
        CampoSenha.setForeground(new java.awt.Color(0, 0, 0));
        CampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome de Usuário");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha");

        botaoEntrar.setBackground(new java.awt.Color(26, 35, 50));
        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoSenha, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 166,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(318, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(botaoEntrar)
                                .addContainerGap(210, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CampoSenhaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_CampoSenhaActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEntrarActionPerformed
        String nome_usuario = campoNomeUsuario.getText();
        String senha = new String(CampoSenha.getPassword());

        ControladorUsuario controladorUsuario = new ControladorUsuario();

        boolean validacao = controladorUsuario.autenticarUsuario(nome_usuario, senha);
        if (validacao == false) {
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            JOptionPane.showMessageDialog(this, "Login feito com sucesso!", "Sucesso", JOptionPane.YES_NO_OPTION);
            TelaPrincipal tela = new TelaPrincipal();
            if (Sessao.getUsuarioLogado().getNivel_usuario() == 0) {
                TelaEscolherClube telaEscolherClube = new TelaEscolherClube(tela, true);
                telaEscolherClube.setVisible(true);
            } else {
                Sessao.setIdClubeAtual(Sessao.getUsuarioLogado().getIdClube());
            }
            tela.setVisible(true);

            frame.dispose();
        }
    }// GEN-LAST:event_botaoEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JTextField campoNomeUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void aplicarEstilosAdicionais() {
        this.removeAll();
        this.setLayout(new java.awt.GridBagLayout());
        this.setBackground(View.Theme.BACKGROUND);

        // painel para o formulario
        javax.swing.JPanel container = new javax.swing.JPanel(new java.awt.GridBagLayout());
        container.setBackground(java.awt.Color.WHITE);
        container.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(View.Theme.CINZA_CLARO_PAINEL, 1),
                new javax.swing.border.EmptyBorder(40, 48, 40, 48)));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(8, 0, 8, 0);
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        gbc.gridx = 0;

        // titulo
        jLabel1.setFont(View.Theme.FONT_TITLE);
        jLabel1.setForeground(View.Theme.CINZA_ESCURO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbc.gridy = 0;
        gbc.insets = new java.awt.Insets(0, 0, 32, 0);
        container.add(jLabel1, gbc);

        gbc.insets = new java.awt.Insets(4, 0, 4, 0);

        // label usuario
        jLabel2.setFont(View.Theme.FONT_TEXT);
        jLabel2.setForeground(View.Theme.CINZA_ESCURO);
        gbc.gridy = 1;
        container.add(jLabel2, gbc);

        // camop usuario
        View.Theme.styleTextField(campoNomeUsuario);
        campoNomeUsuario.setPreferredSize(new java.awt.Dimension(300, 34));
        gbc.gridy = 2;
        gbc.insets = new java.awt.Insets(0, 0, 16, 0);
        container.add(campoNomeUsuario, gbc);

        // label de senha
        jLabel3.setFont(View.Theme.FONT_TEXT);
        jLabel3.setForeground(View.Theme.CINZA_ESCURO);
        gbc.gridy = 3;
        gbc.insets = new java.awt.Insets(4, 0, 4, 0);
        container.add(jLabel3, gbc);

        // campo de senha
        View.Theme.stylePasswordField(CampoSenha);
        CampoSenha.setPreferredSize(new java.awt.Dimension(300, 34));
        gbc.gridy = 4;
        gbc.insets = new java.awt.Insets(0, 0, 32, 0);
        container.add(CampoSenha, gbc);

        // botao de login
        View.Theme.styleButtonPrimary(botaoEntrar);
        botaoEntrar.setPreferredSize(new java.awt.Dimension(300, 36));
        gbc.gridy = 5;
        gbc.insets = new java.awt.Insets(8, 0, 8, 0);
        container.add(botaoEntrar, gbc);

        this.add(container, new java.awt.GridBagConstraints());

        this.revalidate();
        this.repaint();
    }
}
