/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Usuario;

import Controller.ControladorUsuario;
import JDBC.ConnectionFactory;
import Model.Usuario.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mardegan
 */
public class TelaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form TelaUsario
     */
    public TelaUsuario() {
        initComponents();
        configurarAcessos();
        customizarLayout();
    }

    /**
     * Método main temporário para testar a listagem de usuários isoladamente.
     */
    public static void main(String args[]) {
        /* Define o visual (Look and Feel) Nimbus para a tabela ficar bonita */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        /* Cria e exibe o JFrame que conterá o painel da tabela */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frameTeste = new javax.swing.JFrame("Testando Tela de Listagem de Usuários");
                frameTeste.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Instancia o seu painel de listagem
                TelaUsuario painelUsuarios = new TelaUsuario();

                frameTeste.setContentPane(painelUsuarios);

                // Ajusta o tamanho da janela e centraliza no meio do seu monitor
                frameTeste.pack();
                frameTeste.setLocationRelativeTo(null);
                frameTeste.setVisible(true);
            }
        });
    }

    public void atualizarTabela(Usuario usuario) {

        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();

        modelo.setNumRows(0);

        modelo.addRow(new Object[] {
                usuario.getId_usuario(),
                usuario.getNome_usuario(),
                usuario.getNivel_usuario()
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        botaoCadastrar = new javax.swing.JButton();
        botaoListarUsuários = new javax.swing.JButton();
        botaoEditarUsuario = new javax.swing.JButton();
        botaoExcluirUsuario = new javax.swing.JButton();
        botaoBuscarUsuario = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuário");

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "nivel"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuarios);

        botaoCadastrar.setText(" Cadastrar");
        botaoCadastrar.addActionListener(this::botaoCadastrarActionPerformed);

        botaoListarUsuários.setText("Listar Usuários");
        botaoListarUsuários.addActionListener(this::botaoListarUsuáriosActionPerformed);

        botaoEditarUsuario.setText("Editar");
        botaoEditarUsuario.addActionListener(this::botaoEditarUsuarioActionPerformed);

        botaoExcluirUsuario.setText("Excluir");
        botaoExcluirUsuario.addActionListener(this::botaoExcluirUsuarioActionPerformed);

        botaoBuscarUsuario.setText("Buscar");
        botaoBuscarUsuario.addActionListener(this::botaoBuscarUsuarioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoBuscarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(botaoExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoListarUsuários)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoListarUsuários, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEditarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCadastrarActionPerformed
        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaCadastroUsuario telaCadastro = new TelaCadastroUsuario(framePai, true);
        telaCadastro.setVisible(true);
    }// GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoListarUsuáriosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoListarUsuáriosActionPerformed
        ControladorUsuario controladorUsuario = new ControladorUsuario();

        JDBC.ConnectionFactory.iniciarTabelaUsuario();

        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();

        modelo.setNumRows(0);

        ArrayList<Usuario> usuarios = controladorUsuario.listarUsuarios();

        for (Usuario usuario : usuarios) {

            Object[] linha = {
                    usuario.getId_usuario(),
                    usuario.getNome_usuario(),
                    usuario.getNivel_usuario()
            };

            modelo.addRow(linha);
        }

    }// GEN-LAST:event_botaoListarUsuáriosActionPerformed

    private void botaoEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEditarUsuarioActionPerformed
        int linhaSelecionada = tabelaUsuarios.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {
                String nome = tabelaUsuarios.getValueAt(linhaSelecionada, 1).toString();
                Usuario usuario = DataAcessObject.UsuarioDAO.buscarUsuario(nome);

                if (usuario == null) {
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
                    return;
                }

                if (usuario.getId_usuario() != Model.Sessao.getUsuarioLogado().getId_usuario()) {
                    JOptionPane.showMessageDialog(null, "Só é possível editar suas próprias informações.");
                    return;
                }

                java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

                TelaEditarUsuario telaEditarUsuario = new TelaEditarUsuario(framePai, true, usuario.getId_usuario(),
                        usuario.getNome_usuario(), usuario.getSenha(), usuario.getNivel_usuario());

                telaEditarUsuario.setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }

    }// GEN-LAST:event_botaoEditarUsuarioActionPerformed

    private void botaoExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoExcluirUsuarioActionPerformed

        int linhaSelecionada = tabelaUsuarios.getSelectedRow();

        if (linhaSelecionada != -1) {
            try {

                int id = Integer.parseInt(tabelaUsuarios.getValueAt(linhaSelecionada, 0).toString());

                int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o usuário?", "Confirmar Exclusão", javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }

                ControladorUsuario controladorUsuario = new ControladorUsuario();

                ConnectionFactory.iniciarTabelaUsuario();

                controladorUsuario.excluirUsuario(id);
                
                if (id != Model.Sessao.getUsuarioLogado().getId_usuario()) {
                    ((javax.swing.table.DefaultTableModel) tabelaUsuarios.getModel()).removeRow(linhaSelecionada);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma linha");
        }
    }// GEN-LAST:event_botaoExcluirUsuarioActionPerformed

    private void botaoBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoBuscarUsuarioActionPerformed
        java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TelaBuscarUsuario telaBusca = new TelaBuscarUsuario(framePai, true, this);
        telaBusca.setVisible(true);
    }// GEN-LAST:event_botaoBuscarUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarUsuario;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoEditarUsuario;
    private javax.swing.JButton botaoExcluirUsuario;
    private javax.swing.JButton botaoListarUsuários;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables

    private void customizarLayout() {
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(24, 24));
        this.setBackground(View.Theme.BACKGROUND);
        this.setBorder(new javax.swing.border.EmptyBorder(32, 32, 32, 32));

        // Header
        javax.swing.JPanel header = new javax.swing.JPanel(new java.awt.BorderLayout());
        header.setBackground(View.Theme.BACKGROUND);
        
        jLabel1.setFont(View.Theme.FONT_TITLE);
        jLabel1.setForeground(View.Theme.CINZA_ESCURO);
        header.add(jLabel1, java.awt.BorderLayout.WEST);

        // Actions
        javax.swing.JPanel actions = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 12, 0));
        actions.setBackground(View.Theme.BACKGROUND);
        
        View.Theme.styleButtonPrimary(botaoBuscarUsuario);
        View.Theme.styleButtonSecondary(botaoListarUsuários);
        View.Theme.styleButtonSecondary(botaoEditarUsuario);
        View.Theme.styleButtonDanger(botaoExcluirUsuario);
        View.Theme.styleButtonSuccess(botaoCadastrar);
        
        actions.add(botaoBuscarUsuario);
        actions.add(botaoListarUsuários);
        actions.add(botaoEditarUsuario);
        actions.add(botaoExcluirUsuario);
        actions.add(botaoCadastrar);

        header.add(actions, java.awt.BorderLayout.EAST);

        this.add(header, java.awt.BorderLayout.NORTH);

        // Tabela
        View.Theme.styleTable(tabelaUsuarios);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(View.Theme.CINZA_CLARO_PAINEL));
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        this.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    private void configurarAcessos() {
        if (Model.Sessao.getUsuarioLogado() == null) {
            return;
        }
        int nivel = Model.Sessao.getUsuarioLogado().getNivel_usuario();
        if (nivel == 1 || nivel == 2) {
            botaoCadastrar.setEnabled(false);
            botaoExcluirUsuario.setEnabled(false);
        }
    }
}
