/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Partida;

import Controller.ControladorAuditoria;
import Controller.ControladorFinanceiro;
import Controller.ControladorPartida;
import JDBC.ConnectionFactory;
import Model.Partida.Partida;
import Model.Sessao;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;

/**
 *
 * @author mardegan
 */
public class TelaCadastrarPartida extends javax.swing.JDialog {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(TelaCadastrarPartida.class.getName());

        /**
         * Creates new form TelaCadastrarPartida
         */
        public TelaCadastrarPartida(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                painelFundo = new javax.swing.JPanel();
                jLabelTitulo = new javax.swing.JLabel();
                jLabelData = new javax.swing.JLabel();
                jLabelAdversario = new javax.swing.JLabel();
                campoAdversario = new javax.swing.JTextField();
                jLabelGolsMarcados = new javax.swing.JLabel();
                campoGolsMarcados = new javax.swing.JTextField();
                jLabelGolsSofridos = new javax.swing.JLabel();
                campoGolsSofridos = new javax.swing.JTextField();
                jLabelCompeticao = new javax.swing.JLabel();
                campoCompeticao = new javax.swing.JComboBox<>();
                jLabelPremiacao = new javax.swing.JLabel();
                jLabelPublico = new javax.swing.JLabel();
                campoPublico = new javax.swing.JTextField();
                jLabelValorIngresso = new javax.swing.JLabel();
                campoValorIngresso = new javax.swing.JTextField();
                jLabelLocal = new javax.swing.JLabel();
                campoLocal = new javax.swing.JComboBox<>();
                botaoCadastrar = new javax.swing.JButton();
                campoData = new javax.swing.JFormattedTextField();
                campoPremiacao = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Cadastro de Partida");

                painelFundo.setBackground(new java.awt.Color(220, 220, 220));

                jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
                jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
                jLabelTitulo.setText("Cadastro de Partida");

                jLabelData.setForeground(new java.awt.Color(0, 0, 0));
                jLabelData.setText("Data (dd/MM/yyyy)");

                jLabelAdversario.setForeground(new java.awt.Color(0, 0, 0));
                jLabelAdversario.setText("Clube Adversário");

                campoAdversario.setBackground(new java.awt.Color(200, 200, 200));

                jLabelGolsMarcados.setForeground(new java.awt.Color(0, 0, 0));
                jLabelGolsMarcados.setText("Gols Marcados");

                campoGolsMarcados.setBackground(new java.awt.Color(200, 200, 200));

                jLabelGolsSofridos.setForeground(new java.awt.Color(0, 0, 0));
                jLabelGolsSofridos.setText("Gols Sofridos");

                campoGolsSofridos.setBackground(new java.awt.Color(200, 200, 200));

                jLabelCompeticao.setForeground(new java.awt.Color(0, 0, 0));
                jLabelCompeticao.setText("Competição");

                campoCompeticao.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasileirão", "Libertadores",
                                                "Sul-Americana", "Copa do Brasil", "Estadual", "Amistoso" }));

                jLabelPremiacao.setForeground(new java.awt.Color(0, 0, 0));
                jLabelPremiacao.setText("Premiação (R$)");

                jLabelPublico.setForeground(new java.awt.Color(0, 0, 0));
                jLabelPublico.setText("Público");

                campoPublico.setBackground(new java.awt.Color(200, 200, 200));

                jLabelValorIngresso.setForeground(new java.awt.Color(0, 0, 0));
                jLabelValorIngresso.setText("Valor do Ingresso (R$)");

                campoValorIngresso.setBackground(new java.awt.Color(200, 200, 200));

                jLabelLocal.setForeground(new java.awt.Color(0, 0, 0));
                jLabelLocal.setText("Local");

                campoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em casa", "Fora de casa" }));

                botaoCadastrar.setText("Cadastrar");
                botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botaoCadastrarActionPerformed(evt);
                        }
                });

                campoData.setBackground(new java.awt.Color(200, 200, 200));
                try {
                        campoData.setFormatterFactory(
                                        new javax.swing.text.DefaultFormatterFactory(
                                                        new javax.swing.text.MaskFormatter("##/##/####")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                campoData.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                campoDataActionPerformed(evt);
                        }
                });

                campoPremiacao.setBackground(new java.awt.Color(200, 200, 200));

                javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
                painelFundo.setLayout(painelFundoLayout);
                painelFundoLayout.setHorizontalGroup(
                                painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painelFundoLayout.createSequentialGroup()
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(painelFundoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(40, 40, 40)
                                                                                                .addGroup(painelFundoLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(painelFundoLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(painelFundoLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(campoAdversario,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelGolsMarcados,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(campoCompeticao,
                                                                                                                                                                0,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(campoGolsMarcados,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelData,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelAdversario,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelGolsSofridos,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(campoGolsSofridos,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelCompeticao,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(campoData))
                                                                                                                                .addGap(161, 161,
                                                                                                                                                161)
                                                                                                                                .addGroup(painelFundoLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(campoLocal,
                                                                                                                                                                0,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelLocal,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabelPremiacao,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabelPublico,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(campoPublico,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(campoValorIngresso,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                160,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabelValorIngresso)
                                                                                                                                                .addComponent(campoPremiacao)))
                                                                                                                .addGroup(painelFundoLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(182, 182,
                                                                                                                                                182)
                                                                                                                                .addComponent(jLabelTitulo))))
                                                                                .addGroup(painelFundoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(239, 239, 239)
                                                                                                .addComponent(botaoCadastrar)))
                                                                .addContainerGap(53, Short.MAX_VALUE)));
                painelFundoLayout.setVerticalGroup(
                                painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painelFundoLayout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabelTitulo)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelData)
                                                                                .addComponent(jLabelPremiacao))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(campoData,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(campoPremiacao,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                                painelFundoLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabelAdversario)
                                                                                                .addComponent(jLabelPublico))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(
                                                                                painelFundoLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(campoAdversario,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(campoPublico,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(5, 5, 5)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelGolsMarcados)
                                                                                .addComponent(jLabelValorIngresso))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(campoGolsMarcados,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(campoValorIngresso,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelGolsSofridos)
                                                                                .addComponent(jLabelLocal))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(painelFundoLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(campoGolsSofridos,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(campoLocal,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabelCompeticao)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(campoCompeticao,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(botaoCadastrar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(26, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoDataActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_campoDataActionPerformed

        private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCadastrarActionPerformed
                try {
                        String clubeAdversario = campoAdversario.getText().trim();
                        int golsMarcados = -1;
                        try {
                                golsMarcados = Integer.parseInt(campoGolsMarcados.getText().trim());
                        } catch (Exception e) {
                        }
                        int golsSofridos = -1;
                        try {
                                golsSofridos = Integer.parseInt(campoGolsSofridos.getText().trim());
                        } catch (Exception e) {
                        }
                        float premiacao = -1;
                        try {
                                premiacao = Float.parseFloat(campoPremiacao.getText().trim());
                        } catch (Exception e) {
                        }
                        int publico = -1;
                        try {
                                publico = Integer.parseInt(campoPublico.getText().trim());
                        } catch (Exception e) {
                        }
                        float valorDoIngresso = -1;
                        try {
                                valorDoIngresso = Float.parseFloat(campoValorIngresso.getText().trim());
                        } catch (Exception e) {
                        }

                        ControladorPartida controladorPartida = new ControladorPartida();

                        ConnectionFactory.iniciarTabelaPartida();
                        ConnectionFactory.iniciarTabelaTransacao();

                        java.util.Date data = null;
                        try {
                                data = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(campoData.getText().trim());
                        } catch (java.text.ParseException e) {
                        }
                        String competicao = campoCompeticao.getSelectedItem().toString();
                        String local = campoLocal.getSelectedItem().toString();

                        int idPartida = controladorPartida.cadastrarPartida(data, clubeAdversario, golsMarcados,
                                        golsSofridos,
                                        competicao,
                                        premiacao, publico, valorDoIngresso, local);

                        if (idPartida != -1) {
                                ControladorFinanceiro controladorFinanceiro = new ControladorFinanceiro();
                                float bilheteria = controladorFinanceiro.calcularBilheteria(publico, valorDoIngresso);

                                ControladorAuditoria controladorAuditoria = new ControladorAuditoria();

                                controladorAuditoria.registrarAuditoria(Sessao.getUsuarioLogado().getNome_usuario(),
                                                "Partida", "INSERÇÃO", idPartida);

                                if (premiacao > 0) {
                                        controladorFinanceiro.iniciarCadastroDeReceitas("Premiações", premiacao,
                                                        "Premiação da partida contra " + clubeAdversario, "Receita",
                                                        idPartida,
                                                        null);
                                }
                                if (bilheteria > 0) {
                                        controladorFinanceiro.iniciarCadastroDeReceitas("Bilheteria", bilheteria,
                                                        "Bilheteria da partida contra " + clubeAdversario, "Receita",
                                                        idPartida,
                                                        null);
                                }

                                dispose();
                        }
                } catch (NumberFormatException ex) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                        "Preencha os campos numéricos com valores válidos!");
                } catch (Exception ex) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
                }
        }// GEN-LAST:event_botaoCadastrarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botaoCadastrar;
        private javax.swing.JTextField campoAdversario;
        private javax.swing.JComboBox<String> campoCompeticao;
        private javax.swing.JFormattedTextField campoData;
        private javax.swing.JTextField campoGolsMarcados;
        private javax.swing.JTextField campoGolsSofridos;
        private javax.swing.JComboBox<String> campoLocal;
        private javax.swing.JTextField campoPremiacao;
        private javax.swing.JTextField campoPublico;
        private javax.swing.JTextField campoValorIngresso;
        private javax.swing.JLabel jLabelAdversario;
        private javax.swing.JLabel jLabelCompeticao;
        private javax.swing.JLabel jLabelData;
        private javax.swing.JLabel jLabelGolsMarcados;
        private javax.swing.JLabel jLabelGolsSofridos;
        private javax.swing.JLabel jLabelLocal;
        private javax.swing.JLabel jLabelPremiacao;
        private javax.swing.JLabel jLabelPublico;
        private javax.swing.JLabel jLabelTitulo;
        private javax.swing.JLabel jLabelValorIngresso;
        private javax.swing.JPanel painelFundo;
        // End of variables declaration//GEN-END:variables
}
