/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Partida;

import Controller.ControladorPartida;
import JDBC.ConnectionFactory;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;

/**
 *
 * @author mardegan
 */
public class TelaEditarPartida extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(TelaEditarPartida.class.getName());

    /**
     * Creates new form TelaEditarPartida
     */

    private Model.Partida.Partida partidaAtual;

    public TelaEditarPartida(java.awt.Frame parent, boolean modal, Model.Partida.Partida partida) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.partidaAtual = partida;
        preencherDados(partida);
    }

    public void preencherDados(Model.Partida.Partida partida) {
        campoId.setText(String.valueOf(partida.getIdPartida()));
        if (partida.getData() != null) {
            String dataFormatada = new java.text.SimpleDateFormat("dd/MM/yyyy").format(partida.getData());
            campoData.setText(dataFormatada);
        }
        campoAdversario.setText(partida.getClubeAdversario());
        campoGolsMarcados.setText(String.valueOf(partida.getGolsMarcados()));
        campoGolsSofridos.setText(String.valueOf(partida.getGolsSofridos()));
        campoCompeticao.setSelectedItem(partida.getCompeticao());
        campoPremiacao.setText(String.valueOf(partida.getPremiacao()));
        campoPublico.setText(String.valueOf(partida.getPublico()));
        campoValorIngresso.setText(String.valueOf(partida.getValorDoIngresso()));
        campoLocal.setSelectedItem(partida.getLocal());
    }

    public TelaEditarPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelAdversario = new javax.swing.JLabel();
        campoAdversario = new javax.swing.JTextField();
        jLabelGolsMarcados = new javax.swing.JLabel();
        campoGolsMarcados = new javax.swing.JTextField();
        jLabelGolsSofridos = new javax.swing.JLabel();
        campoGolsSofridos = new javax.swing.JTextField();
        jLabelCompeticao = new javax.swing.JLabel();
        campoCompeticao = new javax.swing.JComboBox<>();
        jLabelPremiacao = new javax.swing.JLabel();
        jLabelPublico = new javax.swing.JLabel();
        campoPublico = new javax.swing.JTextField();
        jLabelValorIngresso = new javax.swing.JLabel();
        campoValorIngresso = new javax.swing.JTextField();
        jLabelLocal = new javax.swing.JLabel();
        campoLocal = new javax.swing.JComboBox<>();
        botaoEditar = new javax.swing.JButton();
        campoData = new javax.swing.JFormattedTextField();
        campoPremiacao = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        campoId1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Partida");

        painelFundo.setBackground(new java.awt.Color(220, 220, 220));

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Editar Partida");

        jLabelData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelData.setText("Data (dd/MM/yyyy)");

        jLabelAdversario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAdversario.setText("Clube Adversário");

        campoAdversario.setBackground(new java.awt.Color(200, 200, 200));

        jLabelGolsMarcados.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGolsMarcados.setText("Gols Marcados");

        campoGolsMarcados.setBackground(new java.awt.Color(200, 200, 200));

        jLabelGolsSofridos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGolsSofridos.setText("Gols Sofridos");

        campoGolsSofridos.setBackground(new java.awt.Color(200, 200, 200));

        jLabelCompeticao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCompeticao.setText("Competição");

        campoCompeticao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasileirão", "Libertadores",
                "Sul-Americana", "Copa do Brasil", "Estadual", "Amistoso" }));

        jLabelPremiacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPremiacao.setText("Premiação (R$)");

        jLabelPublico.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPublico.setText("Público");

        campoPublico.setBackground(new java.awt.Color(200, 200, 200));

        jLabelValorIngresso.setForeground(new java.awt.Color(0, 0, 0));
        jLabelValorIngresso.setText("Valor do Ingresso (R$)");

        campoValorIngresso.setBackground(new java.awt.Color(200, 200, 200));

        jLabelLocal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLocal.setText("Local");

        campoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em casa", "Fora de casa" }));

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        campoData.setBackground(new java.awt.Color(200, 200, 200));
        try {
            campoData.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        campoPremiacao.setBackground(new java.awt.Color(200, 200, 200));
        campoPremiacao.setText("jTextField1");

        jLabelId.setForeground(new java.awt.Color(0, 0, 0));
        jLabelId.setText("ID");

        campoId.setEditable(false);
        campoId.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
                painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelFundoLayout.createSequentialGroup()
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelFundoLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(painelFundoLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(painelFundoLayout.createSequentialGroup()
                                                                .addGroup(painelFundoLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(campoAdversario,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(jLabelGolsMarcados,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(campoCompeticao, 0, 160,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(campoGolsMarcados,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(jLabelData,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(jLabelAdversario,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabelGolsSofridos,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(campoGolsSofridos,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(jLabelCompeticao,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(campoData))
                                                                .addGap(161, 161, 161)
                                                                .addGroup(painelFundoLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(campoLocal, 0, 160,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabelLocal,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabelPremiacao,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabelPublico,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(campoPublico,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(campoValorIngresso,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                160, Short.MAX_VALUE)
                                                                        .addComponent(jLabelValorIngresso)
                                                                        .addComponent(campoPremiacao)))
                                                        .addGroup(painelFundoLayout.createSequentialGroup()
                                                                .addGap(182, 182, 182)
                                                                .addComponent(jLabelTitulo))))
                                        .addGroup(painelFundoLayout.createSequentialGroup()
                                                .addGap(239, 239, 239)
                                                .addComponent(botaoEditar)))
                                .addContainerGap(53, Short.MAX_VALUE)));
        painelFundoLayout.setVerticalGroup(
                painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelFundoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelTitulo)
                                .addGap(18, 18, 18)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelData)
                                        .addComponent(jLabelPremiacao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoPremiacao, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelAdversario)
                                                .addComponent(jLabelPublico))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(campoAdversario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(campoPublico, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelGolsMarcados)
                                        .addComponent(jLabelValorIngresso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoGolsMarcados, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoValorIngresso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelGolsSofridos)
                                        .addComponent(jLabelLocal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelFundoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoGolsSofridos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCompeticao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCompeticao, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE)));

        jLabelId1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelId1.setText("ID");

        campoId1.setEditable(false);
        campoId1.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoDataActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEditarActionPerformed
        ControladorPartida controladorPartida = new ControladorPartida();

        ConnectionFactory.iniciarTabelaPartida();

        java.util.Date data = null;
        try {
            data = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(campoData.getText().trim());
        } catch (java.text.ParseException e) {
        }
        String clubeAdversario = campoAdversario.getText();
        int golsMarcados = -1;
        try {
            golsMarcados = Integer.parseInt(campoGolsMarcados.getText());
        } catch (NumberFormatException e) {
        }
        
        int golsSofridos = -1;
        try {
            golsSofridos = Integer.parseInt(campoGolsSofridos.getText());
        } catch (NumberFormatException e) {
        }
        
        String competicao = campoCompeticao.getSelectedItem().toString();
        
        float premiacao = -1f;
        try {
            premiacao = Float.parseFloat(campoPremiacao.getText());
        } catch (NumberFormatException e) {
        }
        
        int publico = -1;
        try {
            publico = Integer.parseInt(campoPublico.getText());
        } catch (NumberFormatException e) {
        }
        
        float valorDoIngresso = -1f;
        try {
            valorDoIngresso = Float.parseFloat(campoValorIngresso.getText());
        } catch (NumberFormatException e) {
        }
        
        String local = campoLocal.getSelectedItem().toString();

        int idPartida = -1;
        try {
            idPartida = Integer.parseInt(campoId.getText());
        } catch (NumberFormatException e) {
        }
        controladorPartida.editarInformacoes(idPartida, data, clubeAdversario, golsMarcados, golsSofridos,
                competicao,
                premiacao, publico, valorDoIngresso, local);

        dispose();

    }// GEN-LAST:event_botaoEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JTextField campoAdversario;
    private javax.swing.JComboBox<String> campoCompeticao;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoGolsMarcados;
    private javax.swing.JTextField campoGolsSofridos;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoId1;
    private javax.swing.JComboBox<String> campoLocal;
    private javax.swing.JTextField campoPremiacao;
    private javax.swing.JTextField campoPublico;
    private javax.swing.JTextField campoValorIngresso;
    private javax.swing.JLabel jLabelAdversario;
    private javax.swing.JLabel jLabelCompeticao;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelGolsMarcados;
    private javax.swing.JLabel jLabelGolsSofridos;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelPremiacao;
    private javax.swing.JLabel jLabelPublico;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValorIngresso;
    private javax.swing.JPanel painelFundo;
    // End of variables declaration//GEN-END:variables
}
